### ISSUE TITLE
Do not use SHA1

### ISSUE THREAD

**Issue by mightypenguin** [ledgerwatch/turbo-geth#1022]
SHA1 is considered insecure/deprecated for use by anyone and especially for a project as important as this.
Please use SHA256 everywhere where possible.

For example look at the latest release notes with Docker images:
https://github.com/ledgerwatch/turbo-geth/releases/tag/v2020.08.04

More info on how to use sha256 with Docker here:
https://stackoverflow.com/questions/32046334/where-can-i-find-the-sha256-code-of-a-docker-image

**Comment by mandrigin** [comment]
Sure, it makes sense.

I want to not that we only used sha1 for publishing hash of the binary inside docker. It wasn’t a hash of the image, but a hash of a binary that you get on linux (if building using go1.15 for x86_64).

I will look up a simple way to provide sha256 of a binary on Alpine. 

The node itself uses a variant of sha3/keccak512 just as Ethereum yellow paper says.

**Comment by mandrigin** [comment]
In the latest release we use sha256 for distribution integirty as was suggested: https://github.com/ledgerwatch/turbo-geth/releases/tag/v2020.09.01

Closing this issue.
