### ISSUE TITLE
Implement storageAt RCP method

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1031]

**Comment by AlexeyAkhunov** [comment]
Should be fixed by this: https://github.com/ledgerwatch/turbo-geth/pull/1048

**Comment by AlexeyAkhunov** [comment]
@Giulio2002 I just looked at the implemented. the `location` (you call it `index` in the signature) needs to be 32-byte hex number, but `uint64`

**Comment by Giulio2002** [comment]
Ok, will fix that

**Comment by Giulio2002** [comment]
> @Giulio2002 I just looked at the implemented. the `location` (you call it `index` in the signature) needs to be 32-byte hex number, but `uint64`

Everything seems to works just fine. The way I coded, it is also implemented in other components though. So maybe we should fix also those.

**Comment by AlexeyAkhunov** [comment]
Now I have tested it, it should be Ok
