### ISSUE TITLE
FR: eth_getTransactionByHash

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/turbo-geth#1035]
During user testing with ArchiveNode.io it looks like some users are relying on `eth_getTransactionByHash`

Can you implement this one?

Thanks!

**Comment by AlexeyAkhunov** [comment]
Should be fixed by https://github.com/ledgerwatch/turbo-geth/pull/1042

**Comment by MysticRyuujin** [comment]
Seems fixed to me
