### ISSUE TITLE
Improve Logging for rpcdaemon

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/turbo-geth#1043]
Currently `rpcdaemon` doesn't seem to have very intuitive logging.

Under normal verbosity (INFO) the only things that really get logged are `WARN` messages. Successful RPC calls are not logged as far as I can tell.

Under higher levels of verbosity (5=detail) I might get something like this:
```
DEBUG[09-03|20:30:27.826] Served eth_getBlockByNumber              conn=47.186.101.185:53502 reqid=1560785948 t=100.562645ms
```

That feels like an INFO to me, not a DEBUG. I would expect a DEBUG to include the actual parameters that were served (E.G. the block number, and the bool in this case).

Even turning on `--debug` didn't change the output of the above 

Ultimately I would like to be able to record both successful and failed RPC requests, including their parameters. I can set whatever verbosity or debug is required, but I also feel like there's room for improvement in general for the default.

**Comment by AskAlexSharov** [comment]
I did first attempt and it seems very hard: 
- our logger does escaping by default, in result log looks like: 
```
TRACE[09-09|12:20:27.473] Served                                   conn=127.0.0.1:56320 method=eth_syncing t=1.395385ms request="{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"eth_syncing\",\"params\":[]}" response="{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":{\"currentBlock\":\"0x0\",\"highestBlock\":\"0xa52f61\"}}"
```
- also now we have no way in code to get current verbosity - it means logging must have no performance penalty
- also now request parsing is separated from response serialization


I wonder if instead of using logs, we can use something similar to Nginx - separated file called `access.log` - where we maybe will write more than just request/response, but also user-agent and maybe some http headers.

**Comment by mandrigin** [comment]
Maybe we can replace geth logs with something like https://github.com/uber-go/zap ?

The api is quite similar but you also get machine readable json logs

**Comment by AskAlexSharov** [comment]
putting json inside json will lead to same problem with symbols escaping.

**Comment by mandrigin** [comment]
You can try serializing json into a map and provide this map to the logger. 

I think zap is generally a better logger than what we have :)

**Comment by AskAlexSharov** [comment]
i'm lazy to change logger :-) 
also json it's not only map, can be array. too much corner cases
let's discuss what can go wrong with this implementation: https://github.com/ledgerwatch/turbo-geth/pull/1087

**Comment by MysticRyuujin** [comment]
So the above was merged, but I'm unclear if I need to bump verbosity to debug in order to get normal/successful RPC request params?

**Comment by AskAlexSharov** [comment]
Yes, verbosity=4
