### ISSUE TITLE
Turboget halted on "peer removal failed"

### ISSUE THREAD

**Issue by koen84** [ledgerwatch/turbo-geth#1056]
Running on Ubuntu 18.04 LTS

```
ERROR[09-05|05:09:02.050] Failed to unregister sync peer           peer=8c061be7f08e9781 err="peer is not registered"
ERROR[09-05|05:09:02.051] Peer unregister failed                   peer=8c061be7f08e9781 err="peer is not registered"
ERROR[09-05|05:09:02.052] Peer removal failed                      peer=8c061be7f08e9781 err="peer is not registered"
```

is the last i see in journal, then the process stalled (10h and counting).

**Comment by AlexeyAkhunov** [comment]
Thanks for reporting! Could it be that you ran out of disk space?
Could you please issue `kill -6 PID` and show us the stack trace?

**Comment by koen84** [comment]
Still plently disk space, but RAM / swap was killing the server, coming from the tg rpcdaemon.  (See #1057 )
Unfortunately i already ran `systemd restart turbogeth`.  Anyway i can still recover the stack trace ?

**Comment by AlexeyAkhunov** [comment]
If the process is killed, then no. I suspect that you got killed by RPC daemon hogging all the memory

**Comment by koen84** [comment]
The process was still running, just didn't process any blocks any more.

Question is, did turbogeth stall and therefore rpcdaemon started hogging all RAM, did rpcdaemon start hogging all RAM and therefore turbogeth stalled, or is it unrelated ?

**Comment by koen84** [comment]
I've seen those lines elsewhere in the log and didn't stall after.  Must've been the RAM hogging.
