### ISSUE TITLE
rpcdaemon eating all RAM

### ISSUE THREAD

**Issue by koen84** [ledgerwatch/turbo-geth#1057]
On ubuntu 18.04 LTS with turbogeth v2020-09_01

The rpcdaemon is using 95,1% of 62GB RAM and i'm 32GB down in swap.

**Comment by AlexeyAkhunov** [comment]
Thanks for reporting! Did you just ran it or you ran lots of queries against it?

**Comment by koen84** [comment]
There's a bunch of queries running against it.  (Testing turbogeth in combo with The Graph.)

**Comment by koen84** [comment]
Rpcdaemon was actively swapping, at peak velocity, server had become unusable.
