### ISSUE TITLE
Add eth_getCode to RPC daemon

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1070]
https://infura.io/docs/ethereum/json-rpc/eth-getCode

**Comment by tjayrush** [comment]
After doing further testing, I found that the code I pushed recently (PR #1100) returns the wrong value for non-contracts. It should return `0x`. It currently returns nothing. Fix incoming...

**Comment by TheAlexCH** [comment]
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_getCode", "params": ["0x2e89a15dCC3da823be9aa40308871850b5b809fF",2], "id":1}' localhost:8545

This is a Smart Contract on Goerli and it returns 0x. 
In fact for every contract I tried, this returns 0x. 

Is that a bug or am I doing something wrong? @tjayrush @AlexeyAkhunov
