### ISSUE TITLE
Add web3_clientVersion to RPC daemon

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1074]
https://infura.io/docs/ethereum/json-rpc/web3-clientVersion

**Comment by tjayrush** [comment]
I'm going to add `web3_sha3` as well with this fix as it's so simple once I'm doing the above.

**Comment by tjayrush** [comment]
I had one small issue that I couldn't figure out with this PR: #1094.

In the [Makefile](https://github.com/ledgerwatch/turbo-geth/blob/1074_web3_clientVersion/Makefile#L69), I wanted to add compile time values for `gitCommit` and `gitDate`, but I wanted to add them directly into the `commands` package. I found this post (https://stackoverflow.com/a/47510909/6307513) about how to do that, but I couldn't get it to work.

I think the only thing I couldn't figure out was the `path` to the commands package. If I had that, I could remove [this](https://github.com/ledgerwatch/turbo-geth/blob/1074_web3_clientVersion/cmd/rpcdaemon/main.go#L14), and [this](https://github.com/ledgerwatch/turbo-geth/blob/1074_web3_clientVersion/cmd/rpcdaemon/main.go#L34), and [this](https://github.com/ledgerwatch/turbo-geth/blob/1074_web3_clientVersion/cmd/rpcdaemon/commands/web3_api.go#L54).

Can someone advise me how to specify the `commands` package in the Makefile?

**Comment by AskAlexSharov** [comment]
@tjayrush here is solution: https://github.com/ethereum/go-ethereum/blob/master/build/ci.go#L269
But don’t include something like time there, because @mandrigin wish to have reproducible builds.

**Comment by AskAlexSharov** [comment]
I think we can have special ‘turbo/version’ package - inject build version there and all code will use it.

**Comment by mandrigin** [comment]
I think I actually broke reproducible builds in the latest version... But we can include commit there but not date (I wonder how that would work for docker builds btw).
