### ISSUE TITLE
Add various missing RPC commands to rpcdaemon

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1075]
https://infura.io/docs/ethereum/json-rpc/eth-chainId

**Comment by MysticRyuujin** [comment]
This is done isn't it?

**Comment by tjayrush** [comment]
Adding:

- [ ] add `eth_chainId`
- [ ] add `eth_gasPrice`
- [ ] add `net_listening` (also move `net_version` into single file)
- [ ] document a few RPC functions that worked but we not previously included
- [ ] Flesh out README.md file (clarify sentences, add implementation table)

**Comment by tjayrush** [comment]
The whole process of adding/documenting/testing the RPC is documented elsewhere. This can be closed.
