### ISSUE TITLE
Add eth-gasPrice to RPC daemon

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1076]
https://infura.io/docs/ethereum/json-rpc/eth-gasPrice

**Comment by tjayrush** [comment]
Moved this issue to #1075. Closing.

**Comment by rainbreak** [comment]
`eth_gasPrice` was not implemented and 1075 is now closed. Is it intentional to omit it, or planned eventually?

**Comment by tjayrush** [comment]
Thanks for noting this. You're right this was an oversight.

This function should report "currently not implemented" but it doesn't.

If you're interested, please feel free to make a PR.
