### ISSUE TITLE
eth_call execution aborted

### ISSUE THREAD

**Issue by akme** [ledgerwatch/turbo-geth#1081]
I've noticed that eth_call is periodically aborted by timeout. The load is the same as before, but I didn't get so many aborts earlier.
Could you please check if any performance issues were introduced in last commits?

#### System information

OS & Version: Linux
Commit hash : commit 9d29a4b480925c34fd98c7e67dd4f7859ea487fb (HEAD -> master, origin/master, origin/HEAD)

#### Actual behaviour
rpcdaemon
```
WARN [09-08|13:46:24.311] Served eth_call                          conn=192.168.240.6:44338   reqid=7914866 t=5.355819233s    err="execution aborted (timeout = 5s)"
WARN [09-08|13:46:29.700] Served eth_call                          conn=192.168.240.6:44452   reqid=7915703 t=5.364825806s    err="execution aborted (timeout = 5s)"
WARN [09-08|13:46:41.269] Served eth_call                          conn=192.168.240.6:44572   reqid=7918133 t=11.534560271s   err="execution aborted (timeout = 5s)"
WARN [09-08|13:46:46.627] Served eth_call                          conn=192.168.240.6:44802   reqid=7918361 t=5.21829811s     err="execution aborted (timeout = 5s)"
WARN [09-08|13:46:52.835] Served eth_call                          conn=192.168.240.6:44858   reqid=7920334 t=5.694729001s    err="execution aborted (timeout = 5s)"
WARN [09-08|13:47:00.891] Served eth_call                          conn=192.168.240.6:44924   reqid=7921049 t=7.781377858s    err="execution aborted (timeout = 5s)"
WARN [09-08|13:47:09.498] Served eth_call                          conn=192.168.240.6:45030   reqid=7921241 t=7.005571924s    err="execution aborted (timeout = 5s)"
WARN [09-08|13:47:17.713] Served eth_call                          conn=192.168.240.6:45256   reqid=7921261 t=6.979736237s    err="execution aborted (timeout = 5s)"
WARN [09-08|13:47:23.166] Served eth_call                          conn=192.168.240.6:45266   reqid=7921262 t=9.769181148s    err="execution aborted (timeout = 5s)"
WARN [09-08|13:49:22.102] Served eth_call                          conn=192.168.240.6:52372   reqid=7934802 t=7.581966328s    err="execution aborted (timeout = 5s)"
WARN [09-08|13:49:29.204] Served eth_call                          conn=192.168.240.6:52438   reqid=7934828 t=7.098433547s    err="execution aborted (timeout = 5s)"
WARN [09-08|13:50:02.386] Served eth_call                          conn=192.168.240.6:52774   reqid=7935034 t=28.241295813s   err="execution aborted (timeout = 5s)"
```
tg
```
INFO [09-08|13:51:35.980] Memory                                   alloc=29.98GiB   sys=48.70GiB
INFO [09-08|13:51:35.980] Timings                                  Headers=137.594852ms   Bodies="418.881µs"  AccountHistoryIndex=86.127571ms   StorageHistoryIndex=100.964701ms TxLookup=154.790395ms Finish="14.786µs"  BlockHashes=2.219005ms      Senders=28.105488ms   Execution=19.507949867s   HashState=41.393936401s IntermediateHashes=1m19.755252414s TxPool=305.039505ms
INFO [09-08|13:52:00.408] Batch                                    commit=24.427807481s
INFO [09-08|13:52:00.703] Commit blocks                            in=24.722581453s
```

![image](https://user-images.githubusercontent.com/1006307/92485800-12538880-f1f4-11ea-9e06-d2916cc9716f.png)

**Comment by AskAlexSharov** [comment]
@akme do you start see timeouts right after node start? Or after long-running period?

**Comment by AlexeyAkhunov** [comment]
Thanks for the report! Can you give examples of what `eth_call` queries you

**Comment by AlexeyAkhunov** [comment]
I suspect this is related to my memory leak fix. Perhaps one of the places I put cancellation was really enforcing the 5s timeout, and it was not enforced before

**Comment by AlexeyAkhunov** [comment]
I can simply increase the timeout and it should work :) Will do the fix shortly

**Comment by AlexeyAkhunov** [comment]
@akme you can try this one: https://github.com/ledgerwatch/turbo-geth/pull/1082

**Comment by akme** [comment]
> @akme do you start see timeouts right after node start? Or after long-running period?

after a long-running period, after node restart, they disappear

> @akme you can try this one: #1082

it's not the problem of timeout setting, but I guess this behavior is affected because of a memory leak or anything else

> Thanks for the report! Can you give examples of what `eth_call` queries you use?

don't have any, they are generated by thegraph node while syncing subgraphs

**Comment by akme** [comment]
a number of requests chart:
![image](https://user-images.githubusercontent.com/1006307/92607240-85c0cd00-f2bc-11ea-8674-34e5779995aa.png)
performance now looks more consistent and not so CPU intensive, but looks like memory is still leaking

**Comment by AlexeyAkhunov** [comment]
So these were `eth_call` requests?

**Comment by akme** [comment]
> So these were `eth_call` requests?

not only, combined

**Comment by AlexeyAkhunov** [comment]
Thanks a lot!
