### ISSUE TITLE
Various additions to RPC Daemon

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/turbo-geth#1084]
The following methods are enabled by `dshackle` be default, so it would be nice to not have to explicitly disable them

- [ ] eth_getUncleCountByBlockHash
- [ ] eth_getUncleCountByBlockNumber
- [ ] eth_getUncleByBlockHashAndIndex
- [ ] eth_getUncleByBlockNumberAndIndex

**Comment by tjayrush** [comment]
Also

- [ ] adding `eth_getTransactionCount`
- [ ] adding various comments to remove VSCode warnings
- [ ] improving README files.
