### ISSUE TITLE
'logIndex' value from eth_getReceipt disagrees with both Geth and Parity

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/turbo-geth#1091]
The value of `logIndex` returned by `eth_getReceipt` disagrees with both Parity and Geth.  For both of those clients, they report the index of the log IN THE BLOCK. TurboGeth reports the index of the log IN THE TRANSACTION.

Parity adds a new field (`transactionLogIndex`) which shows the index of the log in the transaction.

This curl command:

```
curl -s --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x6afbe0f0ea3613edd6b84b71260836c03bddce81604f05c81a070cd671d3d765"],"id":"1"}' -H "Content-Type: application/json" -X POST localhost:8545
```

The image explains more easily:

![image](https://user-images.githubusercontent.com/5417918/92656063-662ba380-f2c0-11ea-9269-dcad43c9ca90.png)

**Comment by tjayrush** [comment]
@AskAlexSharov I know you're going to re-write the Logs related code, but I wonder if you can take a look at this line: https://github.com/ledgerwatch/turbo-geth/blob/master/cmd/rpcdaemon/commands/get_receipts.go#L204.

I find that if I comment out this one line, all the test cases I run that we're previously failing now succeed. I'd like to make a one-line PR to fix this before you do your work, so as you do your work we have test coverage. But I wanted to ask someone else to look it over before I make a PR (so I don't break something else).

I traced back through all the code prior to this line, and it seems to me that this line is incorrectly setting the `logIndex` value that the previous code has already set, but maybe I don't understand something. Thanks.

**Comment by AskAlexSharov** [comment]
I will fix it soon - so, i can get feedback earlier that logic is correct

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/ledgerwatch/turbo-geth/pull/1122
