### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by akme** [ledgerwatch/turbo-geth#1095]
Looks like the memory leak is still there... I resynced node from scratch without any problems, but when I directed requests to tg-node it started to eat up RAM and was killed after an hour of working... 

#### System information

OS & Version: Linux
Commit hash : 62fe81e4be774ae53a658b42f402aea38d98fdbe (HEAD -> master, origin/master, origin/HEAD)

#### Expected behaviour
Just working

#### Actual behaviour
OOM Killed after an hour of working

#### Backtrace

````
[2640205.450390] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-4842.scope,task=tg,pid=1898644,uid=1000
[2640205.450484] Out of memory: Killed process 1898644 (tg) total-vm:4362482372kB, anon-rss:59731216kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:942344kB oom_score_adj:0
[2640207.798699] oom_reaper: reaped process 1898644 (tg), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
````

**Comment by akme** [comment]
Request time response was growing:
![image](https://user-images.githubusercontent.com/1006307/92882034-38597280-f418-11ea-910d-e205736d3003.png)
A number of requests degraded:
![image](https://user-images.githubusercontent.com/1006307/92882177-57f09b00-f418-11ea-9406-10cf4f29a4fd.png)

**Comment by AlexeyAkhunov** [comment]
Thanks for the report! So the leak is inside `tg`, not inside RPC daemon you think?

**Comment by akme** [comment]
This time tg was killed, but some time before rpcdaemon was killed... hard to say need further investigation, any suggestions?

**Comment by akme** [comment]
![image](https://user-images.githubusercontent.com/1006307/92885534-81f78c80-f41b-11ea-8f8d-93897b890161.png)
![image](https://user-images.githubusercontent.com/1006307/92885633-a2274b80-f41b-11ea-895c-0b7b6037b922.png)

**Comment by akme** [comment]
```(pprof) top20
Showing nodes accounting for 23332.43MB, 95.00% of 24561.46MB total
Dropped 578 nodes (cum <= 122.81MB)
Showing top 20 nodes out of 53
      flat  flat%   sum%        cum   cum%
21218.62MB 86.39% 86.39% 22178.45MB 90.30%  time.NewTicker
  959.84MB  3.91% 90.30%   959.84MB  3.91%  time.startTimer
  254.61MB  1.04% 91.33%   254.61MB  1.04%  golang.org/x/crypto/sha3.(*state).clone (inline)
  194.01MB  0.79% 92.12%   194.01MB  0.79%  github.com/ledgerwatch/turbo-geth/core.(*txPricedList).Discard
  167.79MB  0.68% 92.81%   297.18MB  1.21%  google.golang.org/grpc/encoding/proto.marshal
  167.35MB  0.68% 93.49%   167.35MB  0.68%  bytes.makeSlice
  155.80MB  0.63% 94.12% 22737.95MB 92.58%  github.com/ledgerwatch/turbo-geth/ethdb/remote/remotedbserver.(*KvServer).Seek
  129.39MB  0.53% 94.65%   129.39MB  0.53%  google.golang.org/protobuf/proto.MarshalOptions.marshal
   27.50MB  0.11% 94.76%   282.11MB  1.15%  golang.org/x/crypto/sha3.(*state).Sum
      17MB 0.069% 94.83% 22788.95MB 92.78%  google.golang.org/grpc.(*Server).processStreamingRPC
   13.52MB 0.055% 94.89%   343.38MB  1.40%  github.com/ledgerwatch/turbo-geth/p2p.(*rlpxFrameRW).ReadMsg
       6MB 0.024% 94.91%   172.07MB   0.7%  github.com/ledgerwatch/turbo-geth/p2p.(*rlpxFrameRW).WriteMsg
    5.50MB 0.022% 94.93%   160.30MB  0.65%  github.com/ledgerwatch/turbo-geth/eth.(*ProtocolManager).BroadcastTransactions
    4.50MB 0.018% 94.95% 22762.95MB 92.68%  github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1
    2.50MB  0.01% 94.96%   248.35MB  1.01%  github.com/ledgerwatch/turbo-geth/core.(*TxPool).add
    2.50MB  0.01% 94.97%   445.19MB  1.81%  github.com/ledgerwatch/turbo-geth/eth.(*ProtocolManager).handleMsg
    2.50MB  0.01% 94.98%   227.09MB  0.92%  github.com/ledgerwatch/turbo-geth/p2p.updateMAC
    1.50MB 0.0061% 94.99%   279.17MB  1.14%  github.com/ledgerwatch/turbo-geth/eth/fetcher.(*TxFetcher).Enqueue
       1MB 0.0041% 94.99% 22758.45MB 92.66%  github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1
       1MB 0.0041% 95.00%   275.85MB  1.12%  github.com/ledgerwatch/turbo-geth/core.(*TxPool).addTxs```

**Comment by AlexeyAkhunov** [comment]
Thank you! Perhaps the leak is in the transaction pool, I will take a look

**Comment by AlexeyAkhunov** [comment]
I cannot open svg, but I would love to see it. Do you have pprof file perhaps?

**Comment by akme** [comment]
[heap.zip](https://github.com/ledgerwatch/turbo-geth/files/5209414/heap.zip)

[profile001.pdf](https://github.com/ledgerwatch/turbo-geth/files/5209388/profile001.pdf)

**Comment by AlexeyAkhunov** [comment]
Thank you so much, @akme ! You have been very helpful. Looks like gRPC related leak, should be able to fix quickly

**Comment by AlexeyAkhunov** [comment]
This should fix it: https://github.com/ledgerwatch/turbo-geth/pull/1104
We did not close the ticker

**Comment by akme** [comment]
Great! Updated and will watch for it, will close the issue tomorrow if everything is ok.

**Comment by akme** [comment]
Looks like problem solved, thanks!
