### ISSUE TITLE
eth_getBalance returns error message for queries at block 0

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/turbo-geth#1103]
This curl command:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa1e4380a3b1f749673e270229993ee55f35663b4", "0x0"],"id":64}' -H "Content-Type: application/json" <RPC URL>
```
returns this:

```
{"jsonrpc":"2.0","result":"0x6c6b935b8bbd400000","id":64}
```

Against both Parity and Geth.

Against TurboGeth it returns:

```
{"jsonrpc":"2.0","id":64,"error":{"code":-32000,"message":"pending and earliest blocks are not supported"}}
```

If I change [this line](https://github.com/ledgerwatch/turbo-geth/blob/master/turbo/rpchelper/helper.go#L26) from this:

```
		} else if number == rpc.PendingBlockNumber || number == rpc.EarliestBlockNumber {
			return 0, common.Hash{}, fmt.Errorf("pending and earliest blocks are not supported")
```

to

```
		} else if number == rpc.EarliestBlockNumber {
			blockNumber = 0

		} else if number == rpc.PendingBlockNumber {
			return 0, common.Hash{}, fmt.Errorf("pending and earliest blocks are not supported")

```

It works, but I don't know if that's the right thing to do, so I didn't make a PR. I'm curious why [this line](https://github.com/ledgerwatch/turbo-geth/blob/master/turbo/rpchelper/helper.go#L18) returns an error.

**Comment by AlexeyAkhunov** [comment]
Yes, it is ok to fix it as you suggest. I was not sure what to do with that `EarliestBlock` thing, so I just bundled it up with "not supported". When we implement snapshotting, we will need to write it in here

**Comment by tjayrush** [comment]
I'll do this now.
