### ISSUE TITLE
Windows Bug: MDP_MAP_FULL

### ISSUE THREAD

**Issue by joesixpack** [ledgerwatch/turbo-geth#1115]
![image](https://user-images.githubusercontent.com/23145642/93080745-1132b900-f643-11ea-89d7-ff3c164e0c9d.png)

Unlike Linux at 2TB with drastically less disk space, Windows doesn't seem to handle MDP well when set to a drastically smaller size, such as 300GB.

**Comment by AskAlexSharov** [comment]
Hello.

- Please show which command you using to run TG? 
- How big is db file now?
- How much space left on machine?

**Comment by joesixpack** [comment]
.\turbo-geth\build\bin\tg.exe --datadir "D:\\tg_archive" --private.api.addr=localhost:9090 --fakepow --hdd --lmdb.mapSize="180 GB"

chaindata dir is 445GB atm

300GB of space is left on that drive.

Node is not fully synced, its about halfway,

**Comment by AskAlexSharov** [comment]
@joesixpack this parameter sets max limit on db file size: lmdb.mapSize
Set it to 1TB (it can be bigger than disk size).

**Comment by AskAlexSharov** [comment]
Or just remove this parameter

**Comment by AskAlexSharov** [comment]
@joesixpack when you do Ctrl+C in console on windows - do you see message "Database Closed"?

**Comment by joesixpack** [comment]
It doesn't work like on Linux.  Removing it:

![image](https://user-images.githubusercontent.com/23145642/93665114-e40e4e00-fa28-11ea-8345-ead907b46d85.png)

**Comment by AskAlexSharov** [comment]
Then only way to use it on win now is - manually set that flag to right size - which will fit on disk and enoug for work of TG. We don’t have mechanism to automatically increase it slowly.

**Comment by joesixpack** [comment]
Any rules of thumb for what the "right size is"?    It seems to me it wants at least double what the db size is, presumably for the nodes dir.

**Comment by AskAlexSharov** [comment]
I thin 700Gb is not enough for archive node yet, 900Gb probably enough ( https://ledgerwatch.github.io/turbo_geth_release.html#Disk-space )
But if you pass flag —storage-mode=ht then it will 150gb smaller (it will not store logs/receipts)

**Comment by AskAlexSharov** [comment]
Closing for now: 
- we have similar https://github.com/ledgerwatch/turbo-geth/issues/1134
- and we maybe will get dynamic db size soon by mdbx
