### ISSUE TITLE
TG freeze - semacquire

### ISSUE THREAD

**Issue by koen84** [ledgerwatch/turbo-geth#1136]
On ubuntu 18.04 LTS on commit 64e1a8f

Turbogeth was frozen.  This is what i got out of `kill -6 <pid>` which somehow couldn't finish of the process.

```
goroutine 22073198 [semacquire, 649 minutes]:
sync.runtime_SemacquireMutex(0xc0001d2c84, 0xc0277ef400, 0x1)
        runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0001d2c80)
        sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
sync.(*RWMutex).Lock(0xc0001d2c80)
        sync/rwmutex.go:98 +0x90
```

**Comment by AskAlexSharov** [comment]
@koen84 i think this trace is too small to understand where it happened. Do you have bigger trace?

**Comment by koen84** [comment]
I'm afraid this is all i managed to get out of it.  TG was quite stuck, tried a few times kill -6 and that was the extent of what i got, had to resort to more drastic measures.

**Comment by AskAlexSharov** [comment]
@koen84 do you have logs before trace?

**Comment by koen84** [comment]
I grepped through the journal history, but no dice.  I guess this issue is to be closed by lack of intelligible information.

**Comment by AskAlexSharov** [comment]
thank you, closing
