### ISSUE TITLE
Windows: Compiled RPC Daemon Disappears?

### ISSUE THREAD

**Issue by joesixpack** [ledgerwatch/turbo-geth#1156]
Weird stuff:

![image](https://user-images.githubusercontent.com/23145642/94626696-7526c580-0270-11eb-9ada-e73b030ab84d.png)

![image](https://user-images.githubusercontent.com/23145642/94626594-40b30980-0270-11eb-829c-7a3bddb7d61d.png)

**Comment by AlexeyAkhunov** [comment]
Thanks for the report, this is likely due to this change: https://github.com/ledgerwatch/turbo-geth/pull/1153

**Comment by AskAlexSharov** [comment]
Fixed by https://github.com/ledgerwatch/turbo-geth/pull/1158
