### ISSUE TITLE
Add badgerDb as an alternative to BoltDb

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#116]
Badger DB satisfies the main requirements to a database for Turbo-Geth, namely:

1. ACID transactions. This is important for preventing database corruption due to panic, and abrupt shutdowns
2. MVCC (Multi-Version Concurrency Control). This is important for our project of creating a read-only node (with remote over-the-network access to the database of the write-node).

The main difference between BoltDB and BadgerDB is that BoltDB uses B+trees as the data structure, whereas BadgerDB - LSM (Log Structured Merge) trees. We have reasons to believe that LSM trees can perform better with the typical workload of syncing of Turbo-Geth node.

**Comment by yperbasis** [comment]
Also clean up or remove ethdb/table.go
