### ISSUE TITLE
eth_getLogs returns empty

### ISSUE THREAD

**Issue by cvauclair** [ledgerwatch/turbo-geth#1162]
#### System information

Turbogeth version: `2020.10.1-alpha`
OS & Version: `Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux`
Commit hash : `commit 0e62fa4d59e34ccb6b301414d240e1c5ecda4d18` (HEAD of master as of 2020-09-30)

#### Expected behaviour
Command:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock": "0x1e8480", "toBlock": "0x1e8490", "address": "0xec9f6c9634165f91e22e58b90e3ede393d959e47"}],"id":64}' -H "Content-Type: application/json" https://mainnet.infura.io/v3/
```
Return value:
```
{"jsonrpc":"2.0","id":64,"result":[{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","blockHash":"0x7250d1dc6c4b7c1a51f13fb02a92cc60ab1b9592e457ad60813356c656593cc2","blockNumber":"0x1e8484","data":"0x","logIndex":"0x0","removed":false,"topics":["0x95c567a11896e793a41e067198ab5c4a4bdc7b3cf1182571fe911ec7e1426853","0x0000000000000000000000000000000000000000000000000000000000000269","0x000000000000000000000000caac46d9bd68bffb533320545a90cd92c6e98e58"],"transactionHash":"0x9fb710702f0b4d002085994cbb08667bda0f63308174f2cb76f15d93c54a9f67","transactionIndex":"0x2"},{"address":"0xec9f6c9634165f91e22e58b90e3ede393d959e47","blockHash":"0xb2a862fb022e642626f152cd087ae1a895db9486051f22ece96e6b580f86e000","blockNumber":"0x1e8486","data":"0x","logIndex":"0x2","removed":false,"topics":["0xe3e6ac9b8af8d4194beda053cf95abee2ac870c4fb5f26505181ef1d438512bf","0x00000000000000000000000045d01cc478a3dcfd66607726dc50780f3eb4d7bc","0x0000000000000000000000000000000000000000000000000000002e90edd000"],"transactionHash":"0x0bf38cfac67554713083e8ad28b8b64c737a633af2f27b4b68b6033bf504929d","transactionIndex":"0x1"}]}
```

#### Actual behaviour
Command:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock": "0x1e8480", "toBlock": "0x1e8490", "address": "0xec9f6c9634165f91e22e58b90e3ede393d959e47"}],"id":64}' -H "Content-Type: application/json" localhost:8545
```

Return value:
```
{"jsonrpc":"2.0","id":64,"result":[]}
```

#### Steps to reproduce the behaviour
I simply synced my turbogeth node as instructed in https://github.com/ledgerwatch/turbo-geth/blob/master/cmd/rpcdaemon/README.md without any particular flags.

**Comment by tjayrush** [comment]
I can confirm that this is an issue.

As a temporary workaround, I found that if you remove the `address` field from the query, you do get all the logs from the given block (including the ones you're interested in). You can then spin through picking off the logs for that address.

Hope that helps in the meantime.

**Comment by cvauclair** [comment]
Glad to know I'm not the only one affected! 

Also, not sure it it's related to this issue, but I noticed that in my log file for the rpcdaemon I get this warning after calling the `eth_getLogs` method.
```
WARN [09-30|14:12:43.808] Served conn=[::1]:51064 method=eth_getLogs reqid=26294 t=243.557731ms err="rpc error: code = Canceled desc = context canceled"
```

**Comment by AskAlexSharov** [comment]
My setup from same commit - returns 2 results. 

`reqid=26294` - is different from reported by you in 1st comment. So, it means warning not related to your request. 

So. Let's go by next steps:
1. Please show command you used to run TurboGeth (I need to know if you set `--storage-mode` flag).
2. Can you please try again `make rpcdaemon` and restart it. 
3. If step 2 didn't help, run `go run -trimpath ./cmd/hack --action bucketStats --chaindata <your_datadir>/tg/chaindata | grep log` and post results here.

**Comment by tjayrush** [comment]
I just pulled latest master branch and re-ran this command:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock": "0x1e8480", "toBlock": "0x1e8490", "address": "0xec9f6c9634165f91e22e58b90e3ede393d959e47"}],"id":64}' -H "Content-Type: application/json" https://mainnet.infura.io/v3/
```

The problem no longer appears for me. (I get good data.)

**Comment by AlexeyAkhunov** [comment]
I have just tested, though not on master, but on `log_index5`, and it works correctly. I think it should work on master too, maybe there was a confusion with the version you were running, @cvauclair, perhaps your RPC daemon was on one version, but TG was on another (older)?

**Comment by cvauclair** [comment]
Ok I pulled the latest changes and restarted both `tg` and `rpcdaemon` and it works! Thank you!

**Comment by tjayrush** [comment]
I just confirmed again that this now works, and original author of this issue confirms, so closing...
