### ISSUE TITLE
Windows: Error Binding Socket 

### ISSUE THREAD

**Issue by joesixpack** [ledgerwatch/turbo-geth#1170]
This is a consistent problem when starting sometimes (I have it in a loop):

![image](https://user-images.githubusercontent.com/23145642/94889794-41939900-0432-11eb-967b-25b3fb566626.png)

Eventually it "self-corrects".  There's no ghosting of tg.exe

**Comment by AskAlexSharov** [comment]
What is result of: 
netstat -anp | find ":30303"

**Comment by AlexeyAkhunov** [comment]
Perhaps our process does not close the socket when it shuts down. On Windows, it takes the system about 2 mins to tear down the socket if it was not properly closes. If you re-start the process within these two minutes, you will get the error

**Comment by AskAlexSharov** [comment]
Ah... you are right... 
@joesixpack can you try if this version solves your problem: https://github.com/ledgerwatch/turbo-geth/pull/1179

**Comment by joesixpack** [comment]
Aye, it does.
