### ISSUE TITLE
Building storage indices took 23 hours?

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1207]

**Comment by banteg** [comment]
[tg.log](https://github.com/ledgerwatch/turbo-geth/files/5347398/tg.log)

**Comment by AlexeyAkhunov** [comment]
Thank you! I see what the problem was

In your case, the storage index building was tried many times, always from the start, because the process was running out of open file handles:
```
WARN [10-06|13:33:40.893] Synchronisation failed, retrying         err="storage history index: fail to generate index: open /Users/banteg/Library/TurboGeth/etl-temp/tg-sync-sortable-buf474991456: too many open files" 
```

Perhaps it was a mistake to remove the code that maxes up the max open file count...

**Comment by tjayrush** [comment]
I think I have this exact same issue on my Mac. I'm going to try to replace this commit (https://github.com/ledgerwatch/turbo-geth/commit/961b1d57c4efc1cf658ce73fd4050238ea11c767) which removed the code that increased the number of open files allowed. I'll report here and in this issue: https://github.com/ledgerwatch/turbo-geth/issues/1211

**Comment by tjayrush** [comment]
https://github.com/ledgerwatch/turbo-geth/issues/1211#issuecomment-706538117
