### ISSUE TITLE
"fatal error: runtime: out of memory" during ETL [1/2] Extracting

### ISSUE THREAD

**Issue by dafky2000** [ledgerwatch/turbo-geth#1208]
#### System information

Geth version: `2020.10.2-alpha`
OS & Version: Debian 10
Commit hash : 0fb403c0d20e8fd5c4296c62cc165f3d07ad5bbe (#1157, calltraces-index branch)

#### Expected behaviour
Sync blockchain as normal.

#### Actual behaviour
`fatal error: runtime: out of memory` during ETL [1/2] Extracting phase but I am running with about 20gb ram available. From what I can tell there is still plenty of memory available when tg crashes. I was able to sync tg with no issues previously (on master branch a few weeks ago...)

#### Steps to reproduce the behaviour
```bash
git checkout calltraces-index
make all
./build/bin/tg --storage-mode="hrtc"
```

#### Backtrace
Attached log [tg.log](https://github.com/ledgerwatch/turbo-geth/files/5350558/tg.log)

**Comment by AlexeyAkhunov** [comment]
Thanks a lot for the report! It is interesting that you ran it with debug log level, gives us plenty of interesting info :)

**Comment by dafky2000** [comment]
Update/FYI: recently merged into master (ef2353c0e060584ea20c73dc08e2f8e72caf1f2c) is exhibiting the same out of memory issue.

**Comment by AskAlexSharov** [comment]
@dafky2000 , is this issue solved?

**Comment by AlexeyAkhunov** [comment]
I think we can reproduce this. The main clue is that he is doing a very large incremental promotion:
```
INFO [10-08|13:11:11.711] Sync stage 7/14. Generate intermediate hashes and computing state root...
INFO [10-08|13:11:11.711] Generating intermediate hashes           from=9199999  to=11015036
```
Most probably it blows up `exclude` data structure, or `unfurl` here: https://github.com/ledgerwatch/turbo-geth/blob/master/eth/stagedsync/stage_interhashes.go#L228

**Comment by AlexeyAkhunov** [comment]
@dafky2000 Sorry it took me a while to get to this and look at your log file. I think we can now reproduce the problem, and I sort of expected it to happen for some people, but it can and should be fixed.
For you, there might be a workaround. If you run
```
make integration
./build/bin/integration state_ih --reset --chaindata /home/dan/srv/turbogeth/tg/chaindata
```
it should fix this for you and enable you to proceed with your sync, while we think how to best solve the out of memory problem

**Comment by AskAlexSharov** [comment]
Can try again to delete IH instead of collecting unfurl array. Last time with this approach i got “too many dirty pages error” but maybe can find more optimal way to do it...

**Comment by dafky2000** [comment]
I believe **this** issue is resolved! But... I now have a new error.

I had restarted the sync from scratch again and wasn't able to reproduce the original issue but, I ran into a new(?) error. I've attached the log below, not the debug log yet, I'll have to run again with debug enabled.

After running the `integration` command and resyncing, I run into:

```
panic: runtime error: invalid memory address or nil pointer dereference 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0xa67ab1]
 ```

Feel free to close this issue and I can open another :)

[tg.log](https://github.com/ledgerwatch/turbo-geth/files/5416187/tg.log)

**Comment by AskAlexSharov** [comment]
Yes, bug in new stage we recently introduced. Need to fix.

**Comment by dafky2000** [comment]
Sounds good! Looking forward to the fix. Will close this issue and keep my eyes on the merge logs :)

**Comment by AlexeyAkhunov** [comment]
@dafky2000 You are trying to use call tracers, but we are trying to disable it, because it does not work yet :)
