### ISSUE TITLE
Possible incorrect result in debug_getModifiedAccountsByNumber

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/turbo-geth#1232]
This curl command:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"debug_getModifiedAccountsByNumber","params": ["0x2dcaa9", "0x2dcaaa"],"id":64}' -H "Content-Type: application/json" http://localhost:8545
```

(`0x2dcaa9` is block 3001001) returns this data:

```
{
  "id": 64,
  "jsonrpc": "2.0",
  "result": [
    ....
    "0x083696cdfd96f9af4fb5347d82538ef0e617fe8e",
    ....
  ]
}
```

The trouble is, according to Etherscan (and TrueBlocks) account `0x083696cdfd96f9af4fb5347d82538ef0e617fe8e` was not involved in block 3001001, however both ES and TB say it was involved in block 3001002.

I suspect that this is an 'off-by-one' error since the `dbutils.PlainAccountChangeSetBucket` is consulted which I think records changes in the block prior, but I'm not sure.

Perhaps this line needs to add one? https://github.com/ledgerwatch/turbo-geth/blob/master/cmd/rpcdaemon/commands/debug_api.go#L177

**Comment by tjayrush** [comment]
A much simpler example is block 1. There are no transactions and no uncles, so I would think only the miner's account (0x05a56e2d52c817161883f50c441c3228cfe54d9f) should change, but the curl command:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"debug_getModifiedAccountsByNumber","params": ["0x1", "0x2"],"id":64}' -H "Content-Type: application/json" http://localhost:8545
```

returns:

```
{
  "jsonrpc": "2.0",
  "id": 64,
  "result": [
    "0x05a56e2d52c817161883f50c441c3228cfe54d9f",
    "0xdd2f1e6e498202e86d8f5442af596580a4f03c2c"
  ]
}```

It's not clear where the `0xdd...` account comes from.

block 2 returns:

```
{
  "jsonrpc": "2.0",
  "id": 64,
  "result": [
    "0x5088d623ba0fcf0131e0897a91734a4d83596aa0",
    "0xc8ebccc5f5689fa8659d83713341e5ad19349448",
    "0xdd2f1e6e498202e86d8f5442af596580a4f03c2c"
  ]
}
```

but again, there's only a miner (`0xdd2f1e6e498202e86d8f5442af596580a4f03c2c`) and no uncles and no txs.

Maybe it's not an off-by-one alone.

**Comment by AlexeyAkhunov** [comment]
If the correct semantics of this RPC method is that the `params: ["startBlock", "endBlock"]` means that `endBlock` is not inclusive, then definitely yes, there is off-by-one error, and the fix would be to put `>=` instead of `>` here: https://github.com/ledgerwatch/turbo-geth/blob/master/ethdb/walk.go#L102

**Comment by tjayrush** [comment]
When `startBlock` !== `endBlock` it does appear to be inclusive.

When `startBlock` === `endBlock` it does not appear to be inclusive (it reports an error that `end` must be greater than `start`).

Not sure which is intended. I feel like it should be non-inclusive and leave the error message in place.

**Comment by tjayrush** [comment]
https://github.com/ledgerwatch/turbo-geth/blob/master/cmd/rpcdaemon/commands/debug_api.go#L173 implies non-inclusive.

I'll change the line you mentioned above.

I noticed a `method handler crashed` error when giving only one of the two params. I'll try to fix that as well.

**Comment by tjayrush** [comment]
I'll fix this as follows:

- Both `debug_getModifiedAccountsByNumber` and `debug_getModifiedAccountsByNumber` will be inclusive of both the startBlock and the endBlock (or hash).

- Both will allow a single `startBlock` parameter in which case `endBlock` will equal `startBlock` and only that single block will return (not possible before and Number version caused `method response crash`).

- Both will allows `startBlock` to equal `endBlock`, in which case will return a single block (not possible before).

- Note that results appear in order by when the change appeared.

- Note that there may be duplicates in the list if the block range is larger than one block.

PR incoming...
