### ISSUE TITLE
Custom RPC commands should be added to tg_ namespace

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/turbo-geth#1247]
We should add non-standard RPC commands (such as the two `eth_getHeader*` commands and `eth_forkid` to a custom namespace.

Suggestion: `tg_`

1) look for other examples of incorrectly included commands in `eth_`
2) create new API namespace
3) move functions to `eth_tg.go`
4) add tests

**Comment by JekaMas** [comment]
I think logsByHash is also in the list.
