### ISSUE TITLE
command line option to override batch size in execution stage, remove --hdd option

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#1253]
For the experiments with HDD sync and generally for sync efficiency, we need to vary batch size used here: https://github.com/ledgerwatch/turbo-geth/blob/master/eth/stagedsync/stage_execute.go#L165

I suggest we introduce `--stateBatchSize` command line parameter to replace `--hdd` (that would make it easier to find all the places where the change needs to be made). The parsing of the name can be taken from the `--lmdb.mapSize` parameter (so you can specify `--stateBatchSize 100M` for example, instead of always converting to bytes.

**Comment by AlexeyAkhunov** [comment]
Also remove the code that is activated by the `--hdd` parameter, it does not seem to help generally

**Comment by AskAlexSharov** [comment]
Also `mutation.go` must calculate it's size a bit different: 
- Now `p.size += len(skey) + 32 // Add fixed overhead per key`
- Convert to `p.size += len(skey)*2 + 2 // Store key twice in RAM (as bytes and as string) + fixed overhead per key` or do unsafe []byte<->string cast.
