### ISSUE TITLE
Research TG performance ZFS with enabled compression

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/turbo-geth#1262]
We can enable compression 2 ways: 
- in TG code: making code more complex and push everybody to pay price of compress/decompress db rows
- outside of TG code: by enabling some FileSystem compression. Then users can enable compression on their side if they need. But we must be able to answer question - "how well TG will perform on some FS-es with enabled compression?"

Be careful - disable deduplication feature of FS to avoid confusing results.
As I know ZFS default recordsize is 128Kb - need to check if bigger/smaller values are improve performance of TG.

**Comment by AskAlexSharov** [comment]
Work is done:
https://twitter.com/PaoloRebuffo/status/1334110875335217155
https://discord.com/channels/687972960811745322/690898959807283210/792619995724906527

**Comment by aasseman** [comment]
> Work is done: 
https://twitter.com/PaoloRebuffo/status/1334110875335217155 https://discord.com/channels/687972960811745322/690898959807283210/792619995724906527

Both links are dead :(
