### ISSUE TITLE
RPCDaemon: doesn't reconnect after TG 

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/turbo-geth#1265]
Steps to reproduce: 
- run TG and RPCDaemon
- run `echo "POST http://localhost:8545 \n Content-Type: application/json \n @$(pwd)/cmd/rpctest/getLogs.json" | vegeta attack -rate=300 -duration=100s -timeout=1000s | vegeta report`
- RpcDaemon will serve requests well
- Shutdown TG
- RPCDaemon will show in logs: 
```
WARN [10-20|14:23:20.457] Served                                   conn=127.0.0.1:63559 method=eth_getLogs reqid=537758 t="983.258µs" err="getting latest block number: rpc error: code = Unimplemented desc = unknown service remote.KV2"
WARN [10-20|14:23:20.461] received unexpected error from server after CloseSend err="rpc error: code = Unimplemented desc = unknown service remote.KV2"
```
- Start TG 
- RPCDaemon will still show same logs, but it must re-connect and serve new requests successfully
- Please review also code around `CloseSend` method - because as I understand we must see errors earlier (not when closing cursor, probably need hide this error).

**Comment by AlexeyAkhunov** [comment]
I tried it yesterday, and it did reconnect for me, but I had to wait like 30 seconds. Can try again today. I need this functionality for the Sentry, that's why I was testing
