### ISSUE TITLE
TG HasState stage: doesn't gracefully stop on Ctrl+C

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/turbo-geth#1266]
Run HasState stage from scratch, send Ctrl+C, TG will print that it received shutdown signal but will not stop. 
Expected: service to close all resources and stop without errors

**Comment by cyberbono3** [comment]
I would like give this a crack

**Comment by AskAlexSharov** [comment]
great

**Comment by cyberbono3** [comment]
I would like to express my thoughts of the possible solution. Correct me if i am wrong.
I start HashState from scratch [here](https://github.com/ledgerwatch/turbo-geth/blob/master/cmd/integration/main.go#L13). 
Firstly, i have to check that i am running "integration stage_hash_state" (cause my solution relates to HashStage only)
Secondly, i have to implement the service with inbound channel that is triggered [here](https://github.com/ledgerwatch/turbo-geth/blob/c514f9a21463c93fdc5af1e2fb0d260c9cee63d6/cmd/utils/cmd.go#L346). I assume i have to close all resourcers (what exact resourcers?) used in [stageHashState](https://github.com/ledgerwatch/turbo-geth/blob/master/cmd/integration/commands/stages.go#L455) if something comes into my inbound channel. In this case i can call some method to release resourcers e.g. ResetHashState ( i am not sure if it's appropriate method for that). Please advice.

**Comment by AskAlexSharov** [comment]
Almost correct. Here is some context: 
- integration - is a tool for testing - run each stage individually. Main TurboGeth code starts from https://github.com/ledgerwatch/turbo-geth/blob/master/cmd/tg/main.go
- both TurboGeth and integration tool finally calling https://github.com/ledgerwatch/turbo-geth/blob/master/eth/stagedsync/stage_hashstate.go
- this is where problem exists: we pass “quit” channel there (it notified on ctrl+C), but by some reason this stage doesn’t stop (probably we didn’t use “quit” channel in some long loop). 
- About “integration resetHashState” - this command cleaning database tables related to this stage. So, you can use integration (stage_hash_state and reset) for testing. Reset stage and run it from scratch. But target is: to make main TurboGeth process cancelable when it executing this stage.

**Comment by AuraSophia** [comment]
0x40e70857e75F79a4eaE109eD632Ac68FfC6f10Fe
My ethereum adress please

**Comment by AuraSophia** [comment]
![Uploading Screenshot_20210107-165141_Wallet.jpg…]()

**Comment by AuraSophia** [comment]
This is all I have  after git scammed. THEY ARE GOOD, THEY ARE PROFESSIONALS!!! PLEASE IF ANYONE LIKE TO DONATE 1 PLEASE .And thank youuu
