### ISSUE TITLE
Tests: close of close channel

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/turbo-geth#1272]
panic: close of closed channel

goroutine 117 [running]:
github.com/ledgerwatch/turbo-geth/eth/fetcher.(*TxFetcher).Stop(...)
	/Users/alex.sharov/projects/turbo-geth/eth/fetcher/tx_fetcher.go:343
github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).loop.func1(0xc0004ee600)
	/Users/alex.sharov/projects/turbo-geth/eth/sync.go:205 +0x48
github.com/ledgerwatch/turbo-geth/eth.(*chainSyncer).loop(0xc0004ee600)
	/Users/alex.sharov/projects/turbo-geth/eth/sync.go:239 +0x29b
created by github.com/ledgerwatch/turbo-geth/eth.(*ProtocolManager).Start
	/Users/alex.sharov/projects/turbo-geth/eth/handler.go:327 +0x14e
FAIL	github.com/ledgerwatch/turbo-geth/eth	14.139s

**Comment by AlexeyAkhunov** [comment]
Di you try with the latest master? I think this might have something to do with it: https://github.com/ledgerwatch/turbo-geth/pull/1245 @JekaMas what do you think?

**Comment by JekaMas** [comment]
I pretty much sure that I caught the same panic fixing data races in https://github.com/ledgerwatch/turbo-geth/pull/1245/files#diff-e990a3664cf221db4c72bc6c267ef9b7a222fc77e91cc87af415201915bdf1c6R343
@AskAlexSharov Could you check the latest master?

**Comment by AskAlexSharov** [comment]
In master:
```
--- FAIL: TestUDPv5_lookup (5.03s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x44ab879]

goroutine 559 [running]:
testing.tRunner.func1.1(0x45ada40, 0x4a23010)
	/usr/local/Cellar/go/1.15.3/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000583e00)
	/usr/local/Cellar/go/1.15.3/libexec/src/testing/testing.go:1075 +0x41a
panic(0x45ada40, 0x4a23010)
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/panic.go:969 +0x1b9
github.com/ledgerwatch/turbo-geth/p2p/enode.(*DB).fetchUint64(0x0, 0xc00048f230, 0x2a, 0x30, 0x26)
	/Users/alex.sharov/projects/turbo-geth/p2p/enode/nodedb.go:235 +0x99
github.com/ledgerwatch/turbo-geth/p2p/enode.(*DB).localSeq(0x0, 0x22ebdcdb3c25fc28, 0x9f7a7a86967c15c6, 0xb3f531f83f07346c, 0x894e68f9960f01fc, 0x0)
	/Users/alex.sharov/projects/turbo-geth/p2p/enode/nodedb.go:469 +0x116
github.com/ledgerwatch/turbo-geth/p2p/enode.NewLocalNode(0x0, 0xc000219d40, 0x0)
	/Users/alex.sharov/projects/turbo-geth/p2p/enode/localnode.go:78 +0x265
github.com/ledgerwatch/turbo-geth/p2p/discover.(*udpV5Test).getNode(0xc0006fc370, 0xc000219d40, 0xc000322728, 0x0)
	/Users/alex.sharov/projects/turbo-geth/p2p/discover/v5_udp_test.go:590 +0x26e
github.com/ledgerwatch/turbo-geth/p2p/discover.TestUDPv5_lookup(0xc000583e00)
	/Users/alex.sharov/projects/turbo-geth/p2p/discover/v5_udp_test.go:415 +0x2f2
testing.tRunner(0xc000583e00, 0x4674cc8)
	/usr/local/Cellar/go/1.15.3/libexec/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/Cellar/go/1.15.3/libexec/src/testing/testing.go:1168 +0x2b3
```
