### ISSUE TITLE
rpcdaemon debug_accountRange - method handler crashed -  slice bounds out of range [:20] with capacity 8

### ISSUE THREAD

**Issue by qdotme** [ledgerwatch/turbo-geth#1275]
#### System information

OS & Version: Linux 
Commit hash : 716a0f2dbaa5e355c7967b024377922463cdb75f

#### Expected behaviour

debug_accountRange should not crash. 

#### Actual behaviour

````
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"method handler crashed"}}
````

#### Steps to reproduce the behaviour

rpcdaemon connected to tg, tg keeping up with the public ethereum tree. 

````
./build/bin/rpcdaemon --private.api.addr=localhost:9090 --http.api=eth,debug,net,web3 --http.addr=0.0.0.0
````

````
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "debug_accountRange", "params": [10000000, "", 0, false, false, false], "id":1}' localhost:8545
````
#### Backtrace

````
ERROR[10-21|15:39:57.726] RPC method debug_accountRange crashed: runtime error: slice bounds out of range [:20] with capacity 8
goroutine 378813 [running]:
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call.func1(0xc001100a80, 0x12, 0xc000509d50)
        github.com/ledgerwatch/turbo-geth/rpc/service.go:200 +0xba
panic(0x1117d00, 0xc00118bb80)
        runtime/panic.go:969 +0x1b9
github.com/ledgerwatch/turbo-geth/ethdb.(*splitCursor).Next(0xc000126230, 0x24f3bc, 0x6, 0xc0010b1208, 0xc0003217b4, 0x0, 0xc, 0xc0003217b4, 0x844aa0, 0x989681, ...)
        github.com/ledgerwatch/turbo-geth/ethdb/walk.go:92 +0x387
github.com/ledgerwatch/turbo-geth/core/state.NextForChunkedData(0xc0003217e0, 0x14, 0x14, 0x1aabc28, 0x0, 0x0, 0x131bf00, 0xc000126230, 0x989681, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/core/state/history.go:495 +0x4c
github.com/ledgerwatch/turbo-geth/core/state.(*changesetSearchDecorator).Next(0xc0001e0000, 0xc0001143f0, 0x1310760, 0xc0001143f0, 0x1, 0x20, 0x1, 0xc000321700, 0x8, 0xc, ...)
        github.com/ledgerwatch/turbo-geth/core/state/history.go:707 +0x46b
github.com/ledgerwatch/turbo-geth/core/state.walkAsOfThinAccounts(0x1336720, 0xc00119b7c0, 0x11a8259, 0xa, 0x11a11c9, 0x3, 0x1aabc28, 0x0, 0x0, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/core/state/history.go:373 +0xb74
github.com/ledgerwatch/turbo-geth/core/state.WalkAsOf(0x1336720, 0xc00119b7c0, 0x11a8259, 0xa, 0x11a11c9, 0x3, 0x1aabc28, 0x0, 0x0, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/core/state/history.go:134 +0x285
github.com/ledgerwatch/turbo-geth/core/state.(*Dumper).DumpToCollector(0xc0005097e0, 0x131b8c0, 0xc0007f0660, 0x0, 0x1aabc28, 0x0, 0x0, 0x100, 0x0, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/core/state/dump.go:154 +0x2f3
github.com/ledgerwatch/turbo-geth/core/state.(*Dumper).IteratorDump(0xc000ed57e0, 0x1000000, 0x1aabc28, 0x0, 0x0, 0x100, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/core/state/dump.go:272 +0xf8
github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands.(*PrivateDebugAPIImpl).AccountRange(0xc000113710, 0x1329ec0, 0xc000f7d8c0, 0xc001017080, 0x0, 0x0, 0x1aabc28, 0x0, 0x0, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/cmd/rpcdaemon/commands/debug_api.go:101 +0x1de
reflect.Value.call(0xc0001420c0, 0xc000010b78, 0x13, 0x11a15e0, 0x4, 0xc0002b8180, 0x8, 0x8, 0xc0002b81b0, 0xc00108f5f0, ...)
        reflect/value.go:475 +0x8c7
reflect.Value.Call(0xc0001420c0, 0xc000010b78, 0x13, 0xc0002b8180, 0x8, 0x8, 0x16, 0x50, 0x0)
        reflect/value.go:336 +0xb9
github.com/ledgerwatch/turbo-geth/rpc.(*callback).call(0xc0001c37a0, 0x1329ec0, 0xc000f7d8c0, 0xc001100a80, 0x12, 0xc00108f5f0, 0x6, 0x6, 0x0, 0x0, ...)
        github.com/ledgerwatch/turbo-geth/rpc/service.go:206 +0x2c5
github.com/ledgerwatch/turbo-geth/rpc.(*handler).runMethod(0xc00108f4d0, 0x1329ec0, 0xc000f7d8c0, 0xc000370700, 0xc0001c37a0, 0xc00108f5f0, 0x6, 0x6, 0x6)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:388 +0x8a
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCall(0xc00108f4d0, 0xc0007f0450, 0xc000370700, 0xc00041d6c0)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:336 +0x294
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleCallMsg(0xc00108f4d0, 0xc0007f0450, 0xc000370700, 0x131ac01)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:298 +0x1be
github.com/ledgerwatch/turbo-geth/rpc.(*handler).handleMsg.func1(0xc0007f0450)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:139 +0x46
github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc.func1(0xc00108f4d0, 0xc00084d180)
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:226 +0xd2
created by github.com/ledgerwatch/turbo-geth/rpc.(*handler).startCallProc
        github.com/ledgerwatch/turbo-geth/rpc/handler.go:222 +0x66
````

**Comment by AlexeyAkhunov** [comment]
Thanks for the report. I suspect that we need to simplify the implementation a bit, and it should work. The code that is crashing was supposed to protect against inconsistency between changeSet tables and history index tables. This inconsistency now does not happen as long as sync cycle is less than 1024 blocks at a time.

**Comment by qdotme** [comment]
Thanks for quick triage! Let me know if you can't reproduce it / want me to test a branch quickly..

**Comment by tjayrush** [comment]
This is pretty easy to reproduce using the above `curl` command. 

With your example, the code runs to this line https://github.com/ledgerwatch/turbo-geth/blob/master/core/state/history.go#L264 and, if the value of `cmp == 0`, it crashes.

**Comment by tjayrush** [comment]
@qdotme Can you do me a favor? Can you try to run the same `curl` command with the maxResults set to `1` instead of zero? When I do that, it no longer crashes, and I get what appear to be good results.

**Comment by tjayrush** [comment]
The above commit (on this branch https://github.com/ledgerwatch/turbo-geth/tree/1275-debug-accountrange-crash) fixes (more accurately hides) the issue.

**Comment by qdotme** [comment]
Unfortunately, it seems that the 113th' account  (0x0000000000000000000000000000000000021514) or thereabouts are the issue - not the size of the single request - red herring. 

````
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "debug_accountRange", "params": [10000000, "AAAAAAAAAAAAAAAAAAAAAAACFRQ=", 1, true, true, true], "id":1}' localhost:8545
````

still crashes.

**Comment by qdotme** [comment]
And it's also independent on storage-, code-, and preimage- boolean flags.

**Comment by tjayrush** [comment]
Right. So the change I made just hides the issue.

Noting this comment from the Geth issues: https://github.com/ethereum/go-ethereum/pull/17438#issuecomment-414105798

I'm curious, does your command work against Geth? I don't have a Geth node with that API handy.

**Comment by tjayrush** [comment]
This line (https://github.com/ledgerwatch/turbo-geth/blob/account-range/core/state/history.go#L327) assigns `hK0` to be equal to `hK`. The next line tests that `hK` is non-nil and then either that the two keys are equal or the timestamps (actually blockNumbers) is less.

The trouble is `bytes.Equal(hK0, hK)` always returns `true`, which means the second test on that line never gets tested, and as a result every loop advances the cursor.

I'm not sure what the correct behavior should be, but that line does not do what it appears to do.

**Comment by AlexeyAkhunov** [comment]
> The trouble is `bytes.Equal(hK0, hK)` always returns `true`, which means the second test on that line never gets tested, and as a result every loop advances the cursor.

The intended behaviour is to skip away from the `hk0` and find the next `hK` for which the timestamp is >= `timestamp`, so in effect, the next "interesting" record. I had a plan to replace this loop with a `Seek` for better performance, but it will probably be done after we change history index to bitmaps

**Comment by tjayrush** [comment]
But `bytes.Equals(hk, hk0)` always returns `true` (because it was assigned in the previous line). 

So the timestamp check never comes into play (unless I'm reading it wrong...)
