### ISSUE TITLE
eth_getbalance json rpc call always return the same value (the current one)

### ISSUE THREAD

**Issue by fdecollibus** [ledgerwatch/turbo-geth#1346]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Ubuntu 20.04
Commit hash : (if `develop`)

#### Expected behaviour

I am noticing that eth_getbalance does not support other blocks than the last one, is this a desired behaviour?

 curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa1e4380a3b1f749673e270229993ee55f35663b4", "0x0"],"id":64}' -H "Content-Type: application/json" http://localhost:8545
{"jsonrpc":"2.0","id":64,"result":"0x39798f8e51d7a12"}

 curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa1e4380a3b1f749673e270229993ee55f35663b4", "0x19ea66"],"id":64}' -H "Content-Type: application/json" http://localhost:8545
{"jsonrpc":"2.0","id":64,"result":"0x39798f8e51d7a12"}

Instead the balance at that block (1698406) should be different, is this a desidered effect? Looking at the API balances for old blocks seem to be supported. 

Thank you so much for the amazing work

**Comment by tjayrush** [comment]
Thanks so much for reporting this issue. I tried to reproduce the issue, but couldn't.

After updating and building the latest version of Turbo-Geth, I ran these three commands against both Parity and TG:

**For Parity:**

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa1e4380a3b1f749673e270229993ee55f35663b4","0x0"],"id":64}' -H "Content-Type: 
application/json" http://localhost:23456

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa1e4380a3b1f749673e270229993ee55f35663b4","0x19ea66"],"id":64}' -H "Content-Type: 
application/json" http://localhost:23456

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa1e4380a3b1f749673e270229993ee55f35663b4","latest"],"id":64}' -H "Content-Type: 
application/json" http://localhost:23456
```

Results in:

```
{"jsonrpc":"2.0","result":"0x6c6b935b8bbd400000","id":64}
{"jsonrpc":"2.0","result":"0x1bcae3710c1638c06","id":64}
{"jsonrpc":"2.0","result":"0x39798f8e51d7a12","id":64}
```

And for Turbo-Geth:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa1e4380a3b1f749673e270229993ee55f35663b4","0x0"],"id":64}' -H "Content-Type: 
application/json" http://localhost:8545

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa1e4380a3b1f749673e270229993ee55f35663b4","0x19ea66"],"id":64}' -H "Content-Type: 
application/json" http://localhost:8545

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa1e4380a3b1f749673e270229993ee55f35663b4","latest"],"id":64}' -H "Content-Type: 
application/json" http://localhost:8545
```

Results in:

```
{"jsonrpc":"2.0","id":64,"result":"0x6c6b935b8bbd400000"}
{"jsonrpc":"2.0","id":64,"result":"0x1bcae3710c1638c06"}
{"jsonrpc":"2.0","id":64,"result":"0x39798f8e51d7a12"}
```

As you can see both Parity and Turbo-Geth report the same values.

## Debugging

To help me figure this out, perhaps you can provide some further information:

### System information
---
Geth version: `geth version`  
OS & Version: `Windows/Linux/OSX`  
Commit hash:  

### Steps to reproduce the behaviour
---
Also, please try to help me reproduce the issue. I do not see this issue on the latest build.

Run the three commands above and provide the results below.

Also, is the node fully synced?

Have you modified any of the source code yourself?

Also, what exact command did you use to start `turbo-geth`?

What exact command did you use to start the `rpcdaemon`?

**Comment by fdecollibus** [comment]
Thank you so much for your answer. I was pretty sure it completed syncing, but apparently it is missing a last handful of blocks. eth_syncing is still returning 1, and we are at node 11225986

 curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' -H "Content-Type: application/json" http://localhost:8545

{"jsonrpc":"2.0","id":1,"result":{"currentBlock":"0x0","highestBlock":"0xab4b82"}}

I think sync will finish in a couple of hours, I'll try your commands and I'll update the ticket immediately, thanks again for your support

**Comment by tjayrush** [comment]
I guess being fully synced doesn't really matter all that much...your "latest" and my "latest" will be different, so maybe only the first two commands are interesting...

**Comment by fdecollibus** [comment]
Thank you, I've tried again the commands now and they work perfectly, thank you so much for your assistance.
