### ISSUE TITLE
Fix support for Ancient database in turbo-geth

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#137]
There is a support for Ancient database in go-ethereum that requires some refactoring of the database code.

**Comment by komachi** [comment]
Closed as wontfix? Would be awesome to have `--datadir.ancient` flag like in geth.

**Comment by mandrigin** [comment]
Why would you need that?

**Comment by komachi** [comment]
My usecase is to move ancient block to slower hdd and keep chainstate on faster ssd. Ancient block data accessed rarely, but takes a lot of storage. This is supported by bitcoin (`-blocksdir`), geth (`--datadir.ancient`), and other cryptocurrency fullnode implementations.

**Comment by mandrigin** [comment]
yeah, so far we are focusing on getting the basics right. Taking into account that the archive node in TurboGeth uses > 4 times less disk space (under 1TB) and the disk access for most things is way faster than geth (allowing you to just keep a node on HDD potentially), I don’t think that is the top priority for the next couple of months.

After we are sure about the he core functionality of the node, we will revisit the splitting the data storage. As of now, we don’t want to introduce additional complexity there too early. We get a lot of benefit and long term stability from the current data storage being transactional and avoiding inconsistent state even on unexpected shutdowns, etc.
