### ISSUE TITLE
eth_getLogsByHash and tg_getLogsByHash both return same data

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/turbo-geth#1381]
Issue #1380, which I closed, points out that `eth_getLogsByHash` is not part of the **official** eth_ RPC namespace and suggests that it should be renamed to `tg_getLogsByHash`.

It turns out that `tg_getLogsByHash` already exists and returns the same data as `eth_getLogsByHash`. In other words, both exists.

I tried to remove `eth_getLogsByHash`, but it wasn't obvious what was going on. There appears to be only a single routine in the `tg_` namespace.

I tested to see if this `eth_` / `tg_` confusion exists with other APIs, but I didn't find anything.

**Comment by AskAlexSharov** [comment]
about confusion: just need remove 2 things
- method implementation in eth_receipts.go
- and method declaration in eth_api.go

declaration - it's feature of geth rpc framework, no special logic behind it (just allow to switch implementations).
