### ISSUE TITLE
Duplicate configuration ？

### ISSUE THREAD

**Issue by heipacker** [ledgerwatch/turbo-geth#1418]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

package  node/api.go

func (n *Node) apis() []rpc.API {
	return []rpc.API{
		{
			Namespace: "admin",
			Version:   "1.0",
			Service:   &privateAdminAPI{n},
		}, {
			Namespace: "debug",
			Version:   "1.0",
			Service:   debug.Handler,
		}, {
			Namespace: "web3",
			Version:   "1.0",
			Service:   &publicWeb3API{n},
			Public:    true,
		},
	}
}
#### Actual behaviour

package  node/api.go

func (n *Node) apis() []rpc.API {
	return []rpc.API{
		{
			Namespace: "admin",
			Version:   "1.0",
			Service:   &privateAdminAPI{n},
		}, {
			Namespace: "admin",
			Version:   "1.0",
			Service:   &publicAdminAPI{n},
			Public:    true,
		}, {
			Namespace: "debug",
			Version:   "1.0",
			Service:   debug.Handler,
		}, {
			Namespace: "web3",
			Version:   "1.0",
			Service:   &publicWeb3API{n},
			Public:    true,
		},
	}
}
#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
@heipacker , sorry, but I don't understand anything in your message.

**Comment by heipacker** [comment]
there are two paragraphs like  {
Namespace: "admin",
Version: "1.0",
Service: &publicAdminAPI{n},
Public: true,
}

**Comment by AskAlexSharov** [comment]
@heipacker one for privateAdmin, another publicAdmin. 

You can’t call some method?

**Comment by heipacker** [comment]
No problem. I read it wrong
