### ISSUE TITLE
build on windows fails

### ISSUE THREAD

**Issue by Code0x2** [ledgerwatch/turbo-geth#1420]
I followed the "usage" section on the readme.md file, however when I run make tg it fails.

error:
process_begin: CreateProcess(NULL, uname -s, ...) failed.
Makefile:15: pipe: Bad file descriptor
process_begin: CreateProcess(NULL, uname -s, ...) failed.
Makefile:18: pipe: Bad file descriptor
fatal: not a git repository (or any of the parent directories): .git
process_begin: CreateProcess(NULL, uname -s, ...) failed.
Makefile:12: pipe: Bad file descriptor
"Building mdbx"
cd ethdb/mdbx/dist/ && make clean && make mdbx-static.o && cat config.h
make[1]: Entering directory 'C:/Users/x2/tg/ethdb/mdbx/dist'
The system cannot find the path specified.
'case' is not recognized as an internal or external command,
operable program or batch file.
'Darwin*' is not recognized as an internal or external command,
operable program or batch file.
'test' is not recognized as an internal or external command,
operable program or batch file.
'test' is not recognized as an internal or external command,
operable program or batch file.
'test' is not recognized as an internal or external command,
operable program or batch file.
'which' is not recognized as an internal or external command,
operable program or batch file.
rm -rf mdbx_stat mdbx_copy mdbx_dump mdbx_load mdbx_chk mdbx_test @* *.[ao] *.[ls]o *~ tmp.db/* \
        *.gcov *.log *.err src/*.o test/*.o mdbx_example dist \
        config.h src/config.h src/version.c *.tar*
process_begin: CreateProcess(NULL, rm -rf mdbx_stat mdbx_copy mdbx_dump mdbx_load mdbx_chk mdbx_test @* *.[ao] *.[ls]o *~ tmp.db/* *.gcov *.log *.err src/*.o test/*.o mdbx_example dist config.h src/config.h src/version.c *.tar*, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [GNUmakefile:75: clean] Error 2
make[1]: Leaving directory 'C:/Users/x2/tg/ethdb/mdbx/dist'
make: *** [Makefile:37: tg] Error 2 

system:
windows 10 pro

installed packages (from choco)
make, mingw

**Comment by erthink** [comment]
At least the libmdbx for Windows should be build by CMake.
https://github.com/erthink/libmdbx#windows

**Comment by Code0x2** [comment]
> At least the libmdbx for Windows should be build by CMake.
> https://github.com/erthink/libmdbx#windows

so i need to build mdbx first with cmake, then use make tg?

**Comment by erthink** [comment]
> > At least the libmdbx for Windows should be build by CMake.
> > https://github.com/erthink/libmdbx#windows
> 
> so i need to build mdbx first with cmake, then use make tg?
> 
> i tried using cmake but it said missing cmakelists.txt
> 
> how do you suggest building on windows? or am I better off making a vm or using docker for it

My comment to the developers of the turbo-jet, i.e. a hint that they need to modify the build scripts to support Windows.

**Comment by Code0x2** [comment]
> > > At least the libmdbx for Windows should be build by CMake.
> > > https://github.com/erthink/libmdbx#windows
> > 
> > 
> > so i need to build mdbx first with cmake, then use make tg?
> > i tried using cmake but it said missing cmakelists.txt
> > how do you suggest building on windows? or am I better off making a vm or using docker for it
> 
> My comment to the developers of the turbo-jet, i.e. a hint that they need to modify the build scripts to support Windows.

ah. guess ill go put it inside of a vm. would be nice if there were pre built binaries or they put it onto a package manager

**Comment by AskAlexSharov** [comment]
@Code0x2 "would be nice if there were pre built binaries or they put it onto a package manager", you can use docker

**Comment by AskAlexSharov** [comment]
in general - we have poor support for windows: CI doesn't have windows node, developers don't have windows machines, etc... probably we need write about it in Readme.md

**Comment by AskAlexSharov** [comment]
maybe @AndreaLanfranchi can say more

**Comment by AskAlexSharov** [comment]
Yes, after discussion: please use Docker (see docker-compose.yml for more into)
