### ISSUE TITLE
Speedup eth_call by reducing amount of TG calls

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/turbo-geth#1421]
1. ethdb/remote/remotedbserver/server.go:265 - remove common.CopyBytes calls
2. helper.go:GetHashByNumber - no reason to read block here - can call rawdb.ReadCanonicalHash instead of rawdb.ReadBlockByNumber
3. helper.go:GetBlockNumber - can call rawdb.ReadHeaderNumber insttead of rawdb.ReadBlockByHash

**Comment by elliottdehn** [comment]
Is this issue still open, or did the mentioned (merged) issue address it?

**Comment by AskAlexSharov** [comment]
@elliottdehn merged
