### ISSUE TITLE
Disk space needed

### ISSUE THREAD

**Issue by igorline** [ledgerwatch/turbo-geth#1448]
Hi! I've updated my turbo-geth and trying to resync my node, but it seems like disk space needed to sync it is now more than 1TB. Is it correct? Thus makes it impossible to sync node on the hd with 1TB size.

**Comment by igorline** [comment]
I'm getting this error — `WARN [01-20|11:47:53.596] Synchronisation failed, retrying         err="[9/14 StorageHistoryIndex] error writing entries to disk: cbor encode error: write /turbo/data/etl-temp/tg-sync-sortable-buf341581367: no space left on device"`

**Comment by igorline** [comment]
Is there a way to specify `etl-temp` folder location?

**Comment by mandrigin** [comment]
@igorline you can use symlinks or mount another disk there. The path doesn’t change, it’s always this directory under the data dir.
