### ISSUE TITLE
Feature request -- suggestion for new debug RPC method to get account info at specified transaction index

### ISSUE THREAD

**Issue by haltman-at** [ledgerwatch/turbo-geth#1455]
So, I must admit upfront that this feature request isn't really just intended for turbo-geth. :)  Basically @gnidan and I at Truffle were talking about a new debug RPC method we'd like to see... mostly for our own use in Ganache, but we don't like to go just making up new debug RPC methods and putting them in Ganache because, well, we want Ganache to be a good reflection of what one might find on (at least certain) actual Ethereum nodes!  If we write a new Truffle feature, and it relies on an RPC method that only Ganache supports, then it won't work when using Truffle with anything other than Ganache, and we don't want that.  So, that's why we're talking to you rather than just putting it in Ganache and announcing it. :)  Really we should include (non-turbo-)Geth and Besu as well, since they also support debug RPC methods (and it looks like most of them started with Geth, although some seem to have started with Besu), since the idea is that hopefully we'd get everybody to support this -- not sure what the best way to include them here is -- but we saw your announcement of `debug_traceCall` and thought this might be a good place to open the discussion. :)

Anyway, sorry, enough preamble.  The new method we'd like to see -- I'll call it `debug_accountAt`, to give it a name -- is similar to [Besu's `debug_storageRangeAt` method](https://besu.hyperledger.org/en/stable/Reference/API-Methods/#debug_storagerangeat), which I believe Geth and Turbo-Geth both already support (even though it doesn't seem to be in the docs), and which we're currently adding to Ganache.  That method takes a block hash, a transaction index, a contract address, and a storage slot address, and returns the storage in that slot at that transaction index.

What I'd like to see, that I think would be really useful in combination with `debug_storageRangeAt`, would be a method that just takes a block hash, transaction index, and contract address, and returns the account info at that transaction index.  That is to say, it would return a result that includes the account's code, balance, and nonce.  The exact form of the return value is not too important, so long as all the essential information is there.

Basically, a lot of the usefulness of `storageRangeAt` for debugging is that it covers information that's relevant to a transaction but is absent from `debug_traceTransaction`.  So the idea is that `debug_accountAt`, or whatever it ends up being called, would pretty much cover the rest.  Just as we're planning to start having Truffle Debugger start making use of `debug_storageRangeAt` so that it doesn't have to show zeroes for storage that hasn't been touched in the specific transaction, if it had `debug_accountAt` it (and other debuggers) could better handle debugging contracts that had since self-destructed (by getting their code at the relevant transaction index), or `CREATE`s (not `CREATE2`s) that failed (for which determining the address that would have been created requires knowledge of nonces).  Balance isn't particularly essential for anything that any debuggers I know of do at the moment, but tracking balances throughout a transaction is certainly something a debugger might want to do in the future -- it's certainly something we've thought about for Truffle Debugger -- and if we're getting the account information, we may as well get all of it, right?  (I mean, aside from the storage, but that's already its own method! :) )

Anyway, yes, as mentioned above, we were hoping this would make it not only into Turbo-Geth but also Geth and Besu, and of course the idea is we'd add it into Ganache as well, but figured we'd start here. :)  So, hopefully this is something that you agree would be a good addition.  Thank you!

**Comment by haltman-at** [comment]
Also, I am going to tag @davidmurdoch here as well to make sure he sees this. :)

**Comment by AlexeyAkhunov** [comment]
Thank you @haltman-at ! If you suggest the output format for `debug_accountAt`, we might try to implement it

**Comment by haltman-at** [comment]
OK, I'll have to come back and add that later then!  Thank you again!

**Comment by haltman-at** [comment]
OK I will suggest it should basically use the obvious output format. :)  As in, the `result` should be an object with the following properties:
1. `code`: The code for the account, as a `0x`-prefixed hex string;
2. `balance`: The balance for the account, in wei, as an integer;
3. `nonce`: The nonce for the account, as an integer,
4. `codehash`: The code hash for the account, as a `0x`-prefixed hex string.  This is a little redundant, but it seems to me that these debugging methods often are, so I thought it would be nice to include for convenience. :)

Earlier I had been wondering if it should use something more like `debug_storageRangeAt`, but after looking into how that works more I'm pretty sure that no, it should really just be the obvious thing!

**Comment by haltman-at** [comment]
OK, and [here](https://github.com/hyperledger/besu/issues/1892) is where we've now proposed this to Besu as well. :)

**Comment by AlexeyAkhunov** [comment]
Here is what I am getting with my first implementation:
```
 curl -X POST  -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"debug_accountAt","params":["0x57b8dc3fdbaa579e3ddb80671b637e11663cbe00bc1b0e54f252d7380ae786a7", 0, "0xd551234ae421e3bcba99a0da6d736074f22192ff"],"id":1}' http://localhost:8545
```

```
{"jsonrpc":"2.0","id":1,"result":{"balance":"0x3cc62fd5218a9dca388","nonce":"0x3ca1be","code":"0x","codeHash":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"}}
```

```
curl -X POST  -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"debug_accountAt","params":["0x57b8dc3fdbaa579e3ddb80671b637e11663cbe00bc1b0e54f252d7380ae786a7", 1, "0xd551234ae421e3bcba99a0da6d736074f22192ff"],"id":1}' http://localhost:8545
```

```
{"jsonrpc":"2.0","id":1,"result":{"balance":"0x3cc6296d5f2ba422788","nonce":"0x3ca1bf","code":"0x","codeHash":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"}}
```

**Comment by tjayrush** [comment]
Is this just for conviencience?

Couldn't this be done with existing `eth_` RPC commands. `eth_getTransactionByHash(tx_hash)` to get the block number, then `eth_getTransactionCount(account,bn)` to get the nonce, `eth_getCode(account,bn)` to get the code, and `eth_getBalance(account,bn)` to get the balance.  You can even call `web3_sha3` to hash the code.

Just curious what, if anything, is new.

**Comment by haltman-at** [comment]
Ah, sorry, maybe I didn't highlight that part enough.  What's new is that this gets it at a transaction boundary, like `debug_storageRangeAt`, rather than at a block boundary, like the `eth_` methods you mention.

**Comment by tjayrush** [comment]
Oh. I see. Yes. That's new. In fact, I need that!

**Comment by AlexeyAkhunov** [comment]
The feature will be available for first testing in the release today
