### ISSUE TITLE
Chain Head Block in metrics fails to update

### ISSUE THREAD

**Issue by ChosunOne** [ledgerwatch/turbo-geth#1466]
#### System information

Turbogeth version: commit hash 1828bb32faff1778e14e48703307cef9f43aefea
OS & Version: Ubuntu 20.04 Server

#### Expected behavior
The `chain_head_block` metric should update when queried via the http api.

#### Actual behavior
The value reported by `chain_head_block` remains fixed.

#### Steps to reproduce the behavior
1. Sync a tg node and run with metrics enabled
2. Set up a prometheus target at the tg metrics endpoint
3. Query `chain_head_block`
4. Observe as the value remains constant and does not update.

**Comment by AskAlexSharov** [comment]
@ChosunOne done. Also addend many new metrics. Also default grafana dashboard is available.
