### ISSUE TITLE
Int overflow in ethdb/kv_mdbx with Raspbian OS

### ISSUE THREAD

**Issue by thedarkjester** [ledgerwatch/turbo-geth#1485]
#### System information

Geth version: `latest master and latest release 2021.02.01-alpha`
OS & Version: Linux/Raspbian - (Tried ARM64 kernel 8 as well as 32bit 7) (Linux 5.4.83-v8+)  (5.10.11-v7l+)
Commit hash : (if `develop`) 

#### Expected behaviour
Compilation succeeds

#### Actual behaviour
Error on compilation

#### Steps to reproduce the behaviour
Using go compiler 1.5.18 or 1.16rc1 and Raspbian buster OS

```
git clone --recurse-submodules -j8 https://github.com/ledgerwatch/turbo-geth.git && cd turbo-geth
> make tg
> ./build/bin/tg
```

#### Backtrace

````
Building mdbx
make[1]: Entering directory '/home/pi/turbogeth/turbo-geth/ethdb/mdbx/dist'
rm -rf mdbx_stat mdbx_copy mdbx_dump mdbx_load mdbx_chk mdbx_test @* *.[ao] *.[ls]o *.so *.dSYM *~ tmp.db/* \
        *.gcov *.log *.err src/*.o test/*.o mdbx_example dist \
        config.h src/config.h src/version.c *.tar*
make[1]: Leaving directory '/home/pi/turbogeth/turbo-geth/ethdb/mdbx/dist'
make[1]: Entering directory '/home/pi/turbogeth/turbo-geth/ethdb/mdbx/dist'
(echo '#define MDBX_BUILD_TIMESTAMP "2021-02-09T14:07:06+0000"' \
&& echo '#define MDBX_BUILD_FLAGS "-std=gnu++2a -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -Wl,--gc-sections,-z,relro,-O1  -lrt "' \
&& echo '#defi-bash: Building: command not found
ne MDBX_BUILD_COMPILER "cc (Raspbian 8.3.0-6+rpi1) 8.3.0"' \
&& echo '#define MDBX_BUILD_TARGET "arm-linux-gnueabihf"' \
) > config.h
cc -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -DNDEBUG=1 '-DMDBX_CONFIG_H="config.h"' -ULIBMDBX_EXPORTS -c mdbx.c -o mdbx-static.o
make[1]: Leaving directory '/home/pi/turbogeth/turbo-geth/ethdb/mdbx/dist'
#define MDBX_BUILD_TIMESTAMP "2021-02-09T14:07:06+0000"
#define MDBX_BUILD_FLAGS "-std=gnu++2a -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -Wl,--gc-sections,-z,relro,-O1  -lrt "
#define MDBX_BUILD_COMPILER "cc (Raspbian 8.3.0-6+rpi1) 8.3.0"
#define MDBX_BUILD_TARGET "arm-linux-gnueabihf"
env GO111MODULE=on go build -trimpath -o /home/pi/turbogeth/turbo-geth/build/bin/tg -tags "mdbx" -ldflags "-X main.gitCommit=b77dfec05520643696e611adbec8490f6ced7b31" ./cmd/tg
# github.com/ledgerwatch/turbo-geth/ethdb
ethdb/kv_mdbx.go:121:57: constant 2147483648 overflows int
make: *** [Makefile:38: tg] Error 2

````

**Comment by thedarkjester** [comment]
I compiled on 64bit OS Ubuntu for Raspberry Pi separately to this and it compiled successfully. May be a 32bit OS with a 64bit CPU mismatch somewhere in Go?

**Comment by AskAlexSharov** [comment]
you can see all supported architectures by go at: `go tool dist list` and see default target on your setup by `go env GOARCH` and `go env GOOS`.

**Comment by AskAlexSharov** [comment]
also here is some article about ARM support: https://blog.golang.org/ports

**Comment by erthink** [comment]
@AskAlexSharov, там проблема со всеми 32-битными архитектурами, т.е. нужно либо поправить, либо явно требовать 64 бита.

Проблема тривиальная - на 32-битных платформах задаваемый предел размера БД больше чем 32-битный integer.
Причем задавать больше (посредством unsigned) смысла нет, требуется специфическая сборка ядра, 4Gb RAM и другие приседания (не факт что Go runtime не будет глючить и т.п.).
Поэтому лучше брать за основу `mdbx_limits_dbsize_max()` и при необходимости ограничивать полученное значение сверху.

**Comment by AskAlexSharov** [comment]
Yes, agree. No much reason to support 32bit architecture for application with 1Tb of data. I added 64-bits requirement to Readme.

**Comment by thedarkjester** [comment]
Thanks for the replies - I will trash the 32bit OS and go 64bit direct. I am happy to close this - I appreciate the quick replies
