### ISSUE TITLE
Pending transaction is considered as failed on 'DeFi Pulse Index' because of getReceipts error

### ISSUE THREAD

**Issue by annadanchenko** [ledgerwatch/turbo-geth#1503]
Transaction is shown as failed after user buys DPI token on https://www.indexcoop.com/dpi In reality it's not failed but pending and user gets DPI token after it's confirmed. Console contains 

`"error": {
        "code": -32000,
        "message": "getReceipts error: block 0000000000000000000000000000000000000000000000000000000000000000 not found"
    }`

turbo-geth is used as local node and Metamask connects to custom RPC. 

It looks like it happens for any pending transaction. Take any Transaction Hash from https://etherscan.io/txsPending?&m=&p=200 with pending transactions and send request to localhost:8545, e.g. only if `0x4b0686701c7164270a6216bb0446123ed0db1e30ad4626f5b231368bcfc89c60` is pending:

`{
	"jsonrpc": "2.0",
	"id": 121212,
	"method": "eth_getTransactionReceipt",
	"params": ["0x4b0686701c7164270a6216bb0446123ed0db1e30ad4626f5b231368bcfc89c60"]
}`

currently it returns 
`{
    "jsonrpc": "2.0",
    "id": 121212,
    "error": {
        "code": -32000,
        "message": "getReceipts error: block 0000000000000000000000000000000000000000000000000000000000000000 not found"
    }
}`

#### System information

Geth version: `instance=turbo-geth/v2021.02.3-alpha-101c7d78/darwin-amd64/go1.15.6`
OS & Version: MacOS 10.15.7
Commit hash : (if `develop`)

#### Expected behaviour

For pending transaction no errors are returned

#### Actual behaviour

Error is returned for pending transaction for eth_getTransactionReceipt:
`"error": {
        "code": -32000,
        "message": "getReceipts error: block 0000000000000000000000000000000000000000000000000000000000000000 not found"
    }`

This is probably the reason why on `DeFi Pulse Index` transaction is shown as failed right after it was sent. In reality, transaction is not failed and user receives token after it's confirmed.

<img width="1792" alt="Screenshot 2021-02-19 at 11 13 01" src="https://user-images.githubusercontent.com/6584810/108498945-e01f7a00-72ad-11eb-928d-4290e1a242ff.png">

#### Steps to reproduce the behaviour

1. Find tx hash of pending transaction on https://etherscan.io/txsPending?&m=&p=200 
2. Send request to turbo-geth node using pending transaction hash in params. e.g "0x4b0686701c7164270a6216bb0446123ed0db1e30ad4626f5b231368bcfc89c60"
`{
	"jsonrpc": "2.0",
	"id": 121212,
	"method": "eth_getTransactionReceipt",
	"params": ["0x4b0686701c7164270a6216bb0446123ed0db1e30ad4626f5b231368bcfc89c60"]
}`

**Comment by AlexeyAkhunov** [comment]
Thank you very much for this report! If transaction is pending, there is no receipt. What do you think the `eth_getTransactionReceipt` should return in this case, so that DeFi pulse works?

**Comment by mandrigin** [comment]
Isn’t there? I thought it is executed on an euphemeral state before being put in the pool. to validate it and to make sure we don’t spread broken transactions.

I guess we need to take a look what vanilla geth return in that case.

**Comment by annadanchenko** [comment]
@AlexeyAkhunov for similar case if send request to infura.io then there is no error (imo, it can be the expected result):

`
{
    "jsonrpc": "2.0",
    "id": 121212,
    "result": null
}`

**Comment by AlexeyAkhunov** [comment]
Ok, this should be an easy fix then

**Comment by AlexeyAkhunov** [comment]
https://github.com/ledgerwatch/turbo-geth/pull/1505

**Comment by mandrigin** [comment]
@AlexeyAkhunov thanks!

**Comment by mandrigin** [comment]
@annadanchenko can you re-test on the master branch?

**Comment by annadanchenko** [comment]
just waiting for the fees to cool down (atm, it's 0.117 ETH) to make a test

**Comment by annadanchenko** [comment]
can reproduce same error just via sending request (not on actual site)
`WARN [02-23|15:37:10.262] Served                                   conn=127.0.0.1:51549 method=eth_getTransactionReceipt reqid=121212     t=7.844821ms  err="getReceipts error: block 0000000000000000000000000000000000000000000000000000000000000000 not found"`

 instance=turbo-geth/v2021.02.4-alpha-dc6b4c0e/darwin-amd64/go1.15.6

**Comment by annadanchenko** [comment]
please, ignore https://github.com/ledgerwatch/turbo-geth/issues/1503#issuecomment-784249907 I had some cashed termial with rpcdeamon, restarted it and can get expected result 
`{
    "jsonrpc": "2.0",
    "id": 121212,
    "result": null
}`

now just need to verify on the website itself

**Comment by annadanchenko** [comment]
@AlexeyAkhunov @mandrigin fix works fine, retested today with instance=turbo-geth/v2021.02.4-alpha-dc6b4c0e/darwin-amd64/go1.15.6

After sending transaction on DeFi Pulse Index there are expected "pending" and "succeeded" states shown:

<img width="1792" alt="succeeded Screenshot 2021-02-24 at 14 26 23" src="https://user-images.githubusercontent.com/6584810/109007675-b18a1080-76ac-11eb-9e09-449324e6416f.png">
<img width="1792" alt="pending Screenshot 2021-02-24 at 14 22 36" src="https://user-images.githubusercontent.com/6584810/109007694-b6e75b00-76ac-11eb-8ebc-e3beb9762461.png">
