### ISSUE TITLE
Option nousb is deprecated

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ledgerwatch/turbo-geth#1561]
#### System information

Geth version: `2021.03.2-alpha`
OS & Version: Windows
Commit hash : 

#### Expected behaviour

If user does not set cli argument --nousb there should be no warning about its deprecation

#### Actual behaviour

Starting tg **without** `--nousb` cli argument causes a log line to report `Option nousb is deprecated. Use --usb if you want to activate it`

#### Steps to reproduce the behaviour

Start TG

**Comment by AskAlexSharov** [comment]
Fixed: https://github.com/ledgerwatch/turbo-geth/pull/1588
