### ISSUE TITLE
`chain_head_` metrics do not update after startup

### ISSUE THREAD

**Issue by TransmissionsDev** [ledgerwatch/turbo-geth#1615]
# Rationale

`chain_head` metrics are used in the default turbogeth grafana dashboard, yet do not update, it would be easy enough to update these.

# Implementation

<img width="1206" alt="Screen Shot 2021-03-27 at 1 52 41 PM" src="https://user-images.githubusercontent.com/26209401/112734550-b3d9c780-8f03-11eb-817a-2a6dccb687b1.png">

<img width="381" alt="Screen Shot 2021-03-27 at 1 52 31 PM" src="https://user-images.githubusercontent.com/26209401/112734544-ad4b5000-8f03-11eb-98ef-327e76792bab.png">

**Comment by AskAlexSharov** [comment]
Coming soon: https://github.com/ledgerwatch/turbo-geth/pull/1618
With `stage_headers`, `stage_bodies`, `stage_execution` names
