### ISSUE TITLE
Use of --rpc.gascap=0 causes calls to eth_estimateGas to fail

### ISSUE THREAD

**Issue by cryptoDevTrader** [ledgerwatch/turbo-geth#1635]
#### System information

Geth version: `2021.03.02-alpha`
OS & Version: Linux

#### Expected behaviour

Specifying `--rpc.gascap=0` should allow infinite gas to be used for both `eth_call` and `eth_estimateGas`.

#### Actual behaviour

Specifying `--rpc.gascap=0` allows infinite gas to be used for `eth_call`, but sets the gas cap for  `eth_estimateGas` to 0, which causes every call to `eth_estimateGas` to fail.

#### Steps to reproduce the behaviour

1. Start tg with `--private-api.addr`
2. Start rpcdaemon with `--chaindata` and `--private.api.addr` (not sure if this issues is present with just one) and `--rpc.gascap=0`
3. Call `eth_call` that requires a large amount of gas (this should work)
4. Call `eth_estimateGas` for anything (this fails with "gas required exceeds allowance (0)"

**Comment by AskAlexSharov** [comment]
Will take a look today

**Comment by AskAlexSharov** [comment]
fixed, feel free to test
