### ISSUE TITLE
Calling eth_estimateGas with optional second argument (block number or hash) fails

### ISSUE THREAD

**Issue by cryptoDevTrader** [ledgerwatch/turbo-geth#1636]
#### System information

Geth version: `2021.03.02-alpha`
OS & Version: Linux

#### Expected behaviour

Calling `eth_estimateGas` with two arguments (the second being the block number or hash) should estimate gas against the specified block as per https://github.com/ethereum/go-ethereum/issues/2586.

#### Actual behaviour

Calling `eth_estimateGas` with two arguments results in the following error:

```too many arguments, want at most 1``` 

#### Steps to reproduce the behaviour

Call `eth_estimateGas` with a block number or hash as the second argument as per the console binding added in geth at https://github.com/ethereum/go-ethereum/commit/c1544423d655f540b55bb6ec0e7167dad9683c42.

**Comment by AskAlexSharov** [comment]
fixed, feel free to test
