### ISSUE TITLE
[JSON-RPC] Invalid input (-32000) error returned instead of null

### ISSUE THREAD

**Issue by alcuadrado** [ledgerwatch/turbo-geth#1645]
#### System information

Version: `tg version 2021.03.2-alpha`
OS & Version: `Linux puc 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

#### Expected behaviour

These JSON-RPC methods should return `null` when the value is not found. 

* `eth_getTransactionByHash`
* `eth_getTransactionByBlockHashAndIndex`
* `eth_getTransactionByBlockNumberAndIndex`
* `eth_getTransactionReceipt`
* `eth_getBlockByHash`
* `eth_getBlockByNumber`
* `eth_getUncleByBlockHashAndIndex`
* `eth_getUncleByBlockNumberAndIndex`

This is the behavior in, at least, Geth, Ganache, Hardhat Network, and documented in [ethereum.org](https://ethereum.org/en/developers/docs/apis/json-rpc).

#### Actual behaviour

They throw Invalid Input (code: -32000).

#### Steps to reproduce the behaviour

1. Run tg
2. Run `curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0x1111111111111111111111111111111111111111111111111111111111111111"], "id": 1}' localhost:8545`

**Comment by AskAlexSharov** [comment]
Ok :-) Will implement support of this bug today for compatibility. 
Hope users will happy to spend hours to debug "why my server returns null".

**Comment by AskAlexSharov** [comment]
Done in https://github.com/ledgerwatch/turbo-geth/pull/1646
FYI: I changed also this method GetBlockTransactionCountByNumber

**Comment by alcuadrado** [comment]
Wow, that was fast! Thanks!

**Comment by alcuadrado** [comment]
Hey @AskAlexSharov, was this released? I'm asking because there were multiple releases since you fixed it. Thanks!

**Comment by AskAlexSharov** [comment]
Yes
