### ISSUE TITLE
Support parity_getBlockReceipts

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/turbo-geth#1732]
# Rationale

Why should this feature exist?

It exists in Parity/OpenEthereum and Nethermind and it looks like Geth will support it eventually

What are the use-cases?
To get all transaction receipts out of a block without a loop, making a single JSON-RPC call.

# Implementation

Do you have ideas regarding the implementation of this feature?
https://github.com/ethereum/go-ethereum/pull/19721

Are you willing to implement this feature?
:disappointed:

**Comment by AskAlexSharov** [comment]
But we have more complex method - which can filter logs by blocks range and tags. It doesn’t cover this usecase?

**Comment by MysticRyuujin** [comment]
Unfortunately I cannot answer this question. I have to imagine that the people who created the method found it useful, and that the people who use it and asked for it think it's useful, and those tried to implement it in Geth and have started an EIP for it also found it useful.

If they're just doing it wrong, 🤷‍♂️ 

I don't think it matters if Turbo-Geth has a Turbo-Geth specific method, unless tooling accounts for differences in clients.

I wish the APIs were standardized across clients. I dunno.

**Comment by AskAlexSharov** [comment]
@MysticRyuujin 
Done: https://github.com/ledgerwatch/turbo-geth/pull/1735
Can you help me to test `eth_getBlockReceipts` and `eth_getTransactionReceipt` methods plz?
