### ISSUE TITLE
`eth_getBlockReceipts` fails if you try to request immediately after receiving a new head notification

### ISSUE THREAD

**Issue by brianmcgee** [ledgerwatch/turbo-geth#1761]
#### System information

TG version: `master`
OS & Version: Linux
Commit hash : c5162fc3e748303a10bb00bf29bb66e2df34490b

#### Expected behaviour

`eth_getBlockReceipts` returns the list of receipts for the provided block number.

#### Actual behaviour

Sometimes it returns the following error:

```shell
nonce too high: address 0x274F3c32C90517975e29Dfc209a23f315c1e5Fc7, tx: 722226 state: 722223
```

#### Steps to reproduce the behaviour

The issues is non-deterministic, likely some kind of race condition, and only appears to be happening if you are subscribed to new head notifications and attempt to fetch the block receipts on receipt of a notification.

Here is some sample Javascript which can be used to force the issue to occur usually within a few blocks:

```javascript
const Web3 = require('web3');

const web3 = new Web3("ws://...");

web3.extend({
    property: 'eth',
    methods: [{
        name: 'getBlockReceipts',
        call: 'eth_getBlockReceipts',
        params: 1,
        inputFormatter: [web3.extend.formatters.inputDefaultBlockNumberFormatter],
    }]
})

const newHeads = web3.eth.subscribe('newBlockHeaders')

newHeads.on('data', async (header) => {

    const { number, hash } = header
    console.log(`New header, number = ${number}, hash = ${hash}`)

    try {
        const receipts = await web3.eth.getBlockReceipts(header.number)
        console.log('Receipts', receipts.length)
    } catch (err) {
        const { message, stackTrace } = err
        console.error(`Failed to get block receipts for number = ${number}, hash = ${hash}`, message, stackTrace)
        process.exit(1)
    }

})
```

**Comment by AskAlexSharov** [comment]
Thank. Probably I know the reason. Will see.
