### ISSUE TITLE
block number ordering issue on newBlockHeader subscription

### ISSUE THREAD

**Issue by 0xD34D81** [ledgerwatch/turbo-geth#1824]
#### System information

Geth version: `tg version 2021.05.1-alpha`
OS & Version: Linux

#### Expected behaviour

When subscribing to `newBlockHeader`, block numbers should be received in order.

#### Actual behaviour

Sometimes when `tg` receives and processes multiple blocks at the same time, block numbers are not broadcasted in the proper order.

#### Steps to reproduce the behaviour

```
mkdir reproduction
cd reproduction
npm install ethers
```

inside an `index.js` file:

```
const ethers = require('ethers');

const provider = new ethers.providers.WebSocketProvider('ws://127.0.0.1:8545');

const main = async () => {
        let last = Date.now();
        provider.on('block', async (nb) => {
                const logs = await provider.getLogs({
                        fromBlock: nb,
                        toBlock: nb
                });
                console.log('retrieve all block logs', nb, Date.now() - last);
                last = Date.now();
        });
}

main();
```

and run `node index.js`

Sometimes you should see logs like this (displayed values are block number and number of ms since last block event received)

```
retrieve all block logs 12317681 15568
retrieve all block logs 12317683 14
retrieve all block logs 12317682 13
retrieve all block logs 12317684 24022
retrieve all block logs 12317685 16998
retrieve all block logs 12317686 2641
retrieve all block logs 12317687 24495
retrieve all block logs 12317688 1857
retrieve all block logs 12317689 24636
retrieve all block logs 12317690 21911
retrieve all block logs 12317692 94201
retrieve all block logs 12317691 12
retrieve all block logs 12317693 7067
```

**Comment by AskAlexSharov** [comment]
@0xD34D81  Do you think it’s because of reorg, or because of bug in notifications? If first - what behaviour expected?

**Comment by 0xD34D81** [comment]
No, I don’t think it’s reorgs, on geth reorgs would broadcast the same number twice. I believe it’s when tg processes 2 or more blocks at the same time. I’ll try to watch my script and tg at the same time to see If there is some particular behaviour when it happens

**Comment by 0xD34D81** [comment]
Oh wait actually my script moght be wrong as the logging happens after the getLogs call, that might be the issue. I’ll move it before to check.

**Comment by 0xD34D81** [comment]
Properly working, issue was from the getLogs call before logging that baited me into thinking there was an ordering issue
