### ISSUE TITLE
eth_getTransaction not retrieving txpool transactions

### ISSUE THREAD

**Issue by 0xD34D81** [ledgerwatch/turbo-geth#1827]
#### System information

Geth version: `tg version 2021.05.1-alpha`
OS & Version: Linux

#### Expected behaviour

When trying to retrieve a transaction by its transaction hash, and that transaction is a pending transaction provided by the `rpcdaemon`, the transaction details should be returned.

#### Actual behaviour

Pending transaction subscription works properly and provides a continuous flow of pending transactions, but all calls to `eth_getTransaction` are returning `null`.

#### Steps to reproduce the behaviour

```
mkdir reproduction
cd reproduction
npm install ethers
```

in `index.js`:
```
const ethers = require('ethers');

const provider = new ethers.providers.WebSocketProvider('ws://127.0.0.1:8545');

const main = async () => {
        provider.on('pending', async (txhash) => {
                console.log(txhash);
                const tx = await provider.getTransaction(txhash);
                console.log(tx);
        });
}

main();
```

You should see a lot of transaction hashes, but only null values for the `provider.getTransaction(txhash)` call.

**Comment by AskAlexSharov** [comment]
Hi, just added pending transactions support to getTransaction* method: https://github.com/ledgerwatch/turbo-geth/pull/1869

**Comment by 0xD34D81** [comment]
Hi @AskAlexSharov,

tried running the reproduction code again but no event is emitted on the pending transaction subscription.

**Comment by 0xD34D81** [comment]
After commit `d604bfb`, pending transaction hashes are properly broadcasted ! But the `getTransansaction` call is still returning `null` on most calls (this means that on some rare calls it actually retrieves the transaction payload).
