### ISSUE TITLE
trace_transaction and trace_get not working

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/turbo-geth#1833]
This is a tracking issue for the PR.

With the recent changes to `trace_block`, three routines `trace_transaction`, `trace_get`, and `trace_filter` appear to be broken.

**trace_transaction:**
```
curl -s --data '{"method":"trace_transaction","params":["0x6df0b4a0d15ae3b925b9819646a0cff4d1bc0a53b294c0d84d884865302d13a5"],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
```

returns 23 traces from OpenEthereum, but zero from TG.

**trace_get:**
```
curl -s --data '{"method":"trace_get","params":["0x6df0b4a0d15ae3b925b9819646a0cff4d1bc0a53b294c0d84d884865302d13a5",["0x0"]],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
```

returns the first trace of the above, as it should, from OpenEthereum, but nothing from TG.

Note: `trace_filter` is also broken (for the same reason), but I will fix that in a different PR.

**Comment by Uxio0** [comment]
We see the same, more info: https://github.com/gnosis/safe-transaction-service/issues/246

**Comment by tjayrush** [comment]
PR #1835 re-enabled traces for `trace_transaction` and `trace_get`, so I am going to close this issue. There are still a few open issues with tracing. I will create specific issues for those as I fix each one. I'll reference this issue as I create those new issues to make it easier to follow.

**Comment by Uxio0** [comment]
> https://github.com/gnosis/safe-transaction-service/issues/246

I can confirm is now working like OpenEthereum for the case I posted. Thank you for the fix @tjayrush!
