### ISSUE TITLE
Chain stuck after Berlin hardfork

### ISSUE THREAD

**Issue by manuelvillar** [ledgerwatch/turbo-geth#1929]
#### System information

Geth version: instance=turbo-geth/v2021.05.2-alpha-7f51f138/linux-amd64/go1.16
OS & Version: Linux Debian 11.0 (5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux)
Commit hash : (7f51f138)

#### Expected behaviour
Chain continues being updated

#### Actual behaviour
Chain is stuck at:
INFO [05-13|10:58:04.927] [3/14 Bodies] Downloading block bodies   count=65536
ERROR[05-13|10:58:05.227] chain segment could not be inserted, missing parent hash="d87d4e…32722d"
WARN [05-13|10:58:05.228] Synchronisation failed, dropping peer    peer=****some peer id**** err="importBlockResults failed retrieved hash chain is invalid: chain segment could not be inserted, missing parent d87d4e5f06a50d889e7d6d20550ebe49c41b0d312cd5f1557ac8a5331032722d"
ERROR[05-13|10:58:05.228] Ethereum peer removal failed             peer=****some peer id**** err="peer not registered"

#### Steps to reproduce the behaviour
Start tg, problem always reproduces

#### Backtrace

````
[backtrace]
````

**Comment by AlexeyAkhunov** [comment]
Thanks for reporting. This issue has been fixed, but in order to return your database into working state, you need to do these steps:
```
make integration
./build/bin/integration stage_bodies --unwind 1000 --chaindata <your_datadir>/tg/chaindata
```
After that, restart your TG and it should work. If the problem persists, try to increase the unwind value to 2000, etc.

**Comment by manuelvillar** [comment]
Thank you it worked like a charm
