### ISSUE TITLE
Database Repair mode

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#198]
It makes even more sense after this: https://github.com/ledgerwatch/turbo-geth/issues/119

One of the bottlenecks of the archive syncing is the write I/O to the database, exacerbated by various degrees of "write amplification" (we are comparing BoltDB and BadgerDB to see which one has less of it). If the database is only slightly damaged, or needs to be upgraded from the old, slightly incompatible version, it would be more efficient to repair it rather than to resync completely. Because repair workload should most be reading, and occasional writing.

**Comment by Arinerron** [comment]
why'd you close this?

**Comment by AskAlexSharov** [comment]
@Arinerron 
because 1 year passed. DB was changed to db with ACID support - means having db in "bad state" is impossible - unless hardware failure. Erigon can't fix broken hardware.
