### ISSUE TITLE
Occasionally kill doesn't terminate the process 

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/turbo-geth#202]
This might indicate a concurrency issue.

**Comment by yperbasis** [comment]
[out.log.gz](https://github.com/ledgerwatch/turbo-geth/files/3892678/out.log.gz)

**Comment by AlexeyAkhunov** [comment]
https://gist.github.com/AlexeyAkhunov/cf05fb7eeaf2e1e8f6c0702722c469eb
