### ISSUE TITLE
remote.Db remove concept of lastError and return error as an extra value when required

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#224]
`lastError` (which can be retrieved via command `CmdLastError` was originally designed to simplify the interface, but it creates a problem. When something fails on the server side, we would like to "fail fast", i.e. stop the go routine running function `Server` and release the transaction and all other resources. But if we want to allow the client to send `CmdLastError`, we would need to keep it running.
To make it simpler, please return error as an extra return value for the operations that may fail. The client will not need to perform another roundtrip and will the error straight away

**Comment by AskAlexSharov** [comment]
I don't see - how we can make 1 response field optional (without giving to client any signal). 

Here is how popular Databases/Cache storages handling error responses:

- Redis error response:
```
ERROR\r\n 
error_essage\r\n 
```

- MySql error response:
```
0xFF errorr_message
```

- Postgres error response: 
```
E error_message
```

- Memcached error message: 
```
ERROR\r\n
or
CLIENT_ERROR <error>\r\n
or
SERVER_ERROR <error>\r\n
```

So, we may follow the same approach - encode `StatusOk/StatusError` constants as the first field of all responses. Then clients depends on received status will execute different decoding logic. It will give us flexibility to add new response type in future (for example `ClientError`).
