### ISSUE TITLE
Remote DB: Simplify Server function under assumption 1 tx per connection

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#234]
File `ethdb/remote/bolt_remote.go`. Since we now have connection to remoteDb being opened and closed on inside the `View` function on the client side, there is no need to assume that there might be multiple connections per connection on the server side. Therefore `Server` function which deals with 1 client connection can be simplified accordingly

**Comment by AskAlexSharov** [comment]
After implementation of the connection pool - can't simplify server this way. Closing issue.
