### ISSUE TITLE
Special bucket storing database format version - for upgrade tools

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#237]
Came out of consequences of this: https://github.com/ledgerwatch/turbo-geth/issues/220

Create a separate bucket what will contain the version of the Database Layout that the database adheres to. This version will be recognised by the upgrade tools and in future releases, the turbo-geth itself to upgrade the format on the first start, if necessary.

**Comment by AlexeyAkhunov** [comment]
And write this format into the already created snapshots

**Comment by mandrigin** [comment]
Some additional info:
Snapshots are created by the function `saveSnapshot` in `./cmd/state/stateless/stateless.go`.
