### ISSUE TITLE
Analyse the potential benefit of computing codeHash using a merkle tree

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#242]
Code Hash for contract bytecode is currently computed by applying `Keccak256` function to the entire bytecode string of the contract. The main consequence of this for the block witnesses is as follows. For every contract which is invoked during the block's execution, the block witness has to contain the entire bytecode of the contract, even if a very small portion of that code is actually executed. This is because without having the entire code, the witness consumer cannot verify that the CodeHash is correct (and the CodeHash feeds into the computation of the state root of the block witness, so it is necessary to compute).

If the Code Hash were computed using a merkle tree instead, it would be possible to only include some portions of the bytecode into the witness, along with the merkle proof of inclusion of these portions into the Code Hash.

This task is to "pretend" that Code Hash were computed that way, and re-calculate the block witness sizes in such case, to see how much benefit such technique would really bring

**Comment by lithp** [comment]
Dropping a note here, in the telegram group Vitalik brought up a complication which relates to this issue:

> Actually there is another issue, which is that reading any EVM code requires a pass through the entire code to determine which indices are code and which are pushdata
> So accessing any code "in the middle" of a contract would require accessing the whole thing
> So we would need very deep changes to EVM to achieve usable sub-contract-granularity witnesses
