### ISSUE TITLE
RPC test benchmarks to write down stats into a file

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#265]
RPC benchmark driver in `cmd/rpctest/main.go` currently simply writes the request-response roundtrip times to the console, together with the entire request.
For easier analysis, it needs to write the stats into a file, or more files (perhaps one for each side of the comparison), perhaps with request ids,  roundtrip times, and size of the response. Then, extra file for mapping request ids to the request type and info like block number and tx index.

These stats will be then used for statistical analysis on whether a group of rpc deamons connected to one turbo-geth instance is more scalable that one turbo-geth instance on its own

**Comment by AskAlexSharov** [comment]
done
