### ISSUE TITLE
ETC support for TurboGeth

### ISSUE THREAD

**Issue by thomasmodeneis** [ledgerwatch/turbo-geth#270]
Hi there,

I would like to propose to add ETC support for TurboGeth.   
This will include config settings for Mordor, Kotti testnets, and ETC mainnet. 

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by AlexeyAkhunov** [comment]
Hello Thomas!

We did think about the ETC support, and I am sure it would be possible, but it is not currently our priority. Our priority is to make turbo-geth fully functional and "ship" it, then produce documentation on how other implementations can migrate to our data model, which I believe offers superior trade-offs.

We would definitely be interested in contributions that would enable turbo-geth to connect to ETC network, but we cannot currently accommodate this work ourselves.
Hope this helps, Alexey

**Comment by bobsummerwill** [comment]
That is the plan, @AlexeyAkhunov.
For us to contribute the changes to add ETC support to TurboGeth.
Such changes already exist in MultiGeth and should (hopefully) port fairly simply across.
Well - we will try anyway!

**Comment by bobsummerwill** [comment]
Is there a canonical best blog post or "read this" article you have which explains exactly what TurboGeth is going differently, @AlexeyAkhunov?   For everyone who is playing catch-up.

**Comment by AlexeyAkhunov** [comment]
@bobsummerwill We are in the process of creating it. It is currently spit into two documents:
https://github.com/ledgerwatch/turbo-geth/blob/master/docs/programmers_guide/db_walkthrough.MD

https://github.com/ledgerwatch/turbo-geth/blob/master/docs/programmers_guide/guide.md

I am also preparing the road map blog post (look out for it), which I aim to publish before New Year
