### ISSUE TITLE
Sporadic failure in TestFakedSyncProgress62

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/turbo-geth#31]
https://circleci.com/gh/ledgerwatch/turbo-geth/17

--- FAIL: TestFakedSyncProgress62 (1.73s)
    downloader_test.go:1416: final progress mismatch:
        have {StartingBlock:0 CurrentBlock:1004 HighestBlock:1003 PulledStates:0 KnownStates:0}
        want {StartingBlock:0 CurrentBlock:1003 HighestBlock:1003 PulledStates:0 KnownStates:0}

**Comment by b00ris** [comment]
=== CONT  TestForkedSyncProgress62
==================
WARNING: DATA RACE
Read at 0x00c00f0a1e08 by goroutine 90:
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*node).read()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/node.go:204 +0x26a
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Bucket).node()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/bucket.go:834 +0x2de
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Cursor).node()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/cursor.go:556 +0x394
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Bucket).Put()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/bucket.go:313 +0x347
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy.func1.1.1.1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:71 +0x8d
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Bucket).ForEach()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/bucket.go:527 +0x204
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy.func1.1.1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:70 +0xec
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Tx).ForEach.func1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/tx.go:129 +0xa3
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Bucket).ForEach()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/bucket.go:527 +0x204
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Tx).ForEach()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/tx.go:128 +0x78
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy.func1.1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:65 +0x6d
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*DB).View()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/db.go:669 +0xb6
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy.func1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:64 +0x8a
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*DB).Update()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/db.go:638 +0xb6
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:63 +0x1a5
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*testChain).copy()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/testchain_test.go:105 +0xaa7
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*testChain).shorten()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/testchain_test.go:93 +0x82
  github.com/ledgerwatch/turbo-geth/eth/downloader.testForkedSyncProgress()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_test.go:1210 +0x1b6
  github.com/ledgerwatch/turbo-geth/eth/downloader.TestForkedSyncProgress63Full()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_test.go:1196 +0x4a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162

Previous write at 0x00c00f0a1e08 by goroutine 183:
  [failed to restore the stack]

Goroutine 90 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:878 +0x650
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1119 +0xa8
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1117 +0x4ee
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1034 +0x2ee
  main.main()
      _testmain.go:188 +0x221

Goroutine 183 (running) created at:
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:492 +0xd3
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).syncWithPeer()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:482 +0xab5
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).synchronise()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:406 +0x56e
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*downloadTester).sync()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_test.go:98 +0x2cb
  github.com/ledgerwatch/turbo-geth/eth/downloader.testBoundedHeavyForkedSync()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_test.go:656 +0x168
  github.com/ledgerwatch/turbo-geth/eth/downloader.TestBoundedHeavyForkedSync64Light()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_test.go:641 +0x4a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162
==================
==================
WARNING: DATA RACE
Read at 0x00c00b1f9ad8 by goroutine 91:
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*node).read()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/node.go:204 +0x26a
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Bucket).node()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/bucket.go:834 +0x2de
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Cursor).node()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/cursor.go:556 +0x394
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Bucket).Put()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/bucket.go:313 +0x347
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy.func1.1.1.1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:71 +0x8d
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Bucket).ForEach()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/bucket.go:527 +0x204
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy.func1.1.1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:70 +0xec
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Tx).ForEach.func1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/tx.go:129 +0xa3
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Bucket).ForEach()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/bucket.go:527 +0x204
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Tx).ForEach()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/tx.go:128 +0x78
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy.func1.1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:65 +0x6d
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*DB).View()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/db.go:669 +0xb6
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy.func1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:64 +0x8a
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*DB).Update()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/db.go:638 +0xb6
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:63 +0x1a5
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*testChain).copy()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/testchain_test.go:105 +0xaa7
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*testChain).shorten()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/testchain_test.go:93 +0x82
  github.com/ledgerwatch/turbo-geth/eth/downloader.testForkedSyncProgress()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_test.go:1210 +0x1b6
  github.com/ledgerwatch/turbo-geth/eth/downloader.TestForkedSyncProgress64Full()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_test.go:1199 +0x4a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162

Previous write at 0x00c00b1f9ad8 by goroutine 146:
  [failed to restore the stack]

Goroutine 91 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:878 +0x650
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1119 +0xa8
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1117 +0x4ee
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1034 +0x2ee
  main.main()
      _testmain.go:188 +0x221

Goroutine 146 (running) created at:
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:492 +0xd3
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).syncWithPeer()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:482 +0xab5
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).synchronise()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:406 +0x56e
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*downloadTester).sync()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_test.go:98 +0x2cb
  github.com/ledgerwatch/turbo-geth/eth/downloader.testForkedSyncProgress.func2()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_test.go:1228 +0x94
==================
    testing.go:771: race detected during execution of test

**Comment by JekaMas** [comment]
[test.txt](https://github.com/ledgerwatch/turbo-geth/files/3257253/test.txt)

The data race:
Read side:
```
Read at 0x00c00b1f9ad8 by goroutine 91:
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*node).read()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/node.go:204 +0x26a
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Bucket).node()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/bucket.go:834 +0x2de
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Cursor).node()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/cursor.go:556 +0x394
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Bucket).Put()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/bucket.go:313 +0x347
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy.func1.1.1.1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:71 +0x8d
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Bucket).ForEach()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/bucket.go:527 +0x204
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy.func1.1.1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:70 +0xec
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Tx).ForEach.func1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/tx.go:129 +0xa3
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Bucket).ForEach()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/bucket.go:527 +0x204
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*Tx).ForEach()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/tx.go:128 +0x78
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy.func1.1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:65 +0x6d
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*DB).View()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/db.go:669 +0xb6
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy.func1()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:64 +0x8a
  github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt.(*DB).Update()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/vendor/github.com/ledgerwatch/bolt/db.go:638 +0xb6
  github.com/ledgerwatch/turbo-geth/ethdb.(*BoltDatabase).MemCopy()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/ethdb/memory_database.go:63 +0x1a5
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*testChain).copy()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/testchain_test.go:105 +0xaa7
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*testChain).shorten()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/testchain_test.go:93 +0x82
  github.com/ledgerwatch/turbo-geth/eth/downloader.testForkedSyncProgress()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_test.go:1210 +0x1b6
  github.com/ledgerwatch/turbo-geth/eth/downloader.TestForkedSyncProgress64Full()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_test.go:1199 +0x4a
```

Write side:
```
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).spawnSync()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:492 +0xd3
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).syncWithPeer()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:482 +0xab5
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*Downloader).synchronise()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader.go:406 +0x56e
  github.com/ledgerwatch/turbo-geth/eth/downloader.(*downloadTester).sync()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_test.go:98 +0x2cb
  github.com/ledgerwatch/turbo-geth/eth/downloader.testForkedSyncProgress.func2()
      /home/b00ris/go/src/github.com/ledgerwatch/turbo-geth/eth/downloader/downloader_test.go:1228 +0x94
```

One of the fetchers functions created in `downloader.go` `syncWithPeer()` method uses `boltdb` to write something.

**Comment by b00ris** [comment]
write side:
ethdb/memory_database.go:59
```func (db *BoltDatabase) MemCopy() Database {
	logger := log.New("database", "in-memory")

	// Open the db and recover any potential corruptions
	mem, err := bolt.Open("in-memory", 0600, &bolt.Options{MemOnly: true})
	if err != nil {
		panic(err)
	}
	/*
	if err := mem.Update(func(memTx *bolt.Tx) error {
		return db.db.View(func(tx *bolt.Tx) error {
			return tx.ForEach(func(name []byte, b *bolt.Bucket) error {
				memB, err := memTx.CreateBucket(name, true)
				if err != nil {
					return err
				}
				return b.ForEach(func(k, v []byte) error {
					if err := memB.Put(k, v); err != nil {
						return err
					}
					return nil
				})
			})
		})
	}); err != nil {
		panic(err)
	}*/
	return &BoltDatabase{
		fn:  "in-memory",
		db:  mem,
		log: logger,
	}
}
```

**Comment by JekaMas** [comment]
The Boltdb readme says:
"Individual transactions and all objects created from them (e.g. buckets, keys) are not thread safe. To work with data in multiple goroutines you must start a transaction for each one or use locking to ensure only one goroutine accesses a transaction at a time. Creating transaction from the DB is thread safe."
