### ISSUE TITLE
Can we enforce static jumps and subroutines by simple heuristics?

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#339]
We would like to check the hypothesis that most (or perhaps all) smart contracts deployed on the mainnet can be "statically" analysed to compute, for each jump instruction, very small number of static destinations. It is my belief that developers do not really use the "computation of the jump destination" a lot, if at all. At the moment i can think of 3 heuristics which could cover most of the cases:
1. Obvious static jump. It is a sequence of `PUSHn <destination>` and `JUMP/JUMPI`
2. Subroutine pattern. Since EVM does not support subroutines, the generated code emulates them, by doing `PUSHn <return_destinantion>`, then executing the subroutine inline (or jumping to it), making sure that at the end, the `return destination` is at the top of the stack. Then, as a return from the subroutine, `JUMP/JUMPI` is used. We can analyse this by tracking the jump destination "backwards" from `JUMP/JUMPI` and proving that it can always take one of the limited set of values that are known up-front (these values correspond to each place where the subroutine is called).
3. Invalid jumps. I believe that before the special `INVALID` opcode was introduced, jumps to some obviously wrong destinations were used to abort transactions. For example, if a program is compiled with Solidity, it is known that destination `02` is an invalid destination, because all compiled solidity programs started with `PUSH x PUSH y MSTORE`, so no `JUMPDEST`

The result of this research should be the answer to the question on how many contracts cannot be covered by these heuristics, or new heuristic(s) that would cover those. If we can cover all existing contracts, and the heuristics can be implemented efficiently, we can announce a hard-fork after which all contracts will be validated on deployment, and if they are not valid according to those heuristics, they will not deploy.

**Comment by gacolvin** [comment]
I doubt the answer is yes, but the data will still be interesting.  Don't forget that code can beget new code, so you have to be sure that no such code will be misbegotten.
