### ISSUE TITLE
Re-execute all historical transaction in read-only mode and check ChangeSets

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#340]
In order to support RPC `debug_traceTransaction` call, and for other tracing facilities, we have this file: https://github.com/ledgerwatch/turbo-geth/blob/master/core/state/readonly.go

It defines type `DbState` that is similar to `TrieDbState`, but does not have any functionality to write to the database, and also it does not have the trie cache.

We would like to use it to retrace all historical transactions, in the way it was used in here: https://github.com/ledgerwatch/turbo-geth/blob/master/cmd/state/stateless/naked_accouts.go

But without actually calculating the naked accounts etc.

In order to make sure that the execution is correct, we need to extend `DbState` type to track account changes and contract storage changes during an execution of a block, so that at the end of the block, we can compare them with what we have in the `ChangeSet` buckets.

NOTE: The part that collects changes and compares to `ChangeSet` buckets needs to be optional, so when we are sure the execution works correctly, we turn it off for better performance

**Comment by yperbasis** [comment]
I've found 1 problem so far. Contract [0x04b39C2a507AC2Fc091eEE0c4379B341d890c1dd](https://etherscan.io/address/0x04b39c2a507ac2fc091eee0c4379b341d890c1dd) was created at block 156614, but AccountsHistoryBucket only contains an empty entry for it at block 156634.

**Comment by yperbasis** [comment]
0x04b39c2a507ac2fc091eee0c4379b341d890c1dd was killed in block 156634, and there were actually 2 transactions invoking the kill. Then in CommitBlock only UpdateAccountData was called (not DeleteAccount) with original.Initialised = false, thus putting an empty record into AccountsHistoryBucket, thus implying that the account didn't exist prior to block 156634.

**Comment by yperbasis** [comment]
I've fixed the previous issue. Now there's a new problem in block 9235355 (w/o thin history) 
[check.log](https://github.com/ledgerwatch/turbo-geth/files/4455899/check.log)
