### ISSUE TITLE
Remove storage Root from the Account DB records

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#458]
Can to be removed in favour of corresponding record in IntermediateHash bucket. Which also makes a lot of sense if we want to make our structure hex/bin merkle tree flexible
the only thing that will be merkle-tree type dependent is the IntermediateHash bucket

**Comment by AskAlexSharov** [comment]
Done by https://github.com/ledgerwatch/turbo-geth/pull/504
