### ISSUE TITLE
panic: invalid page type: 0: 0

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/turbo-geth#554]
INFO [05-17|09:28:16.058] Block synchronisation started 
INFO [05-17|09:28:19.844] Inserting chain                          start=7732920 end=7732921 current=7732919 currentHeader=7732919
panic: invalid page type: 0: 0

goroutine 1393 [running]:
github.com/ledgerwatch/bolt.(*Cursor).search(0xc0007af500, 0xc02d910a56, 0x3, 0x3, 0x46ebfab)
        /home/andrey_ashikhmin/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.5-0.20200504044242-1f3c42ebc79a/cursor.go:393 +0x441
github.com/ledgerwatch/bolt.(*Cursor).searchPage(0xc0007af500, 0xc02d910a56, 0x3, 0x3, 0x7f4d3ac61000)
        /home/andrey_ashikhmin/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.5-0.20200504044242-1f3c42ebc79a/cursor.go:516 +0x328
github.com/ledgerwatch/bolt.(*Cursor).search(0xc0007af500, 0xc02d910a56, 0x3, 0x3, 0xb96c61)
        /home/andrey_ashikhmin/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.5-0.20200504044242-1f3c42ebc79a/cursor.go:410 +0x148
github.com/ledgerwatch/bolt.(*Cursor).seekTo(0xc0007af500, 0xc02d910a56, 0x3, 0x3, 0x7f5049c507e1, 0x3, 0x3, 0xc0007af240, 0x47302c, 0x3, ...)
        /home/andrey_ashikhmin/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.5-0.20200504044242-1f3c42ebc79a/cursor.go:269 +0x2a9
github.com/ledgerwatch/bolt.(*Cursor).SeekTo(0xc0007af500, 0xc02d910a56, 0x3, 0x3, 0x3, 0x3, 0x1, 0x7f5049c507e1, 0x3, 0x3)
        /home/andrey_ashikhmin/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.5-0.20200504044242-1f3c42ebc79a/cursor.go:145 +0x67
github.com/ledgerwatch/turbo-geth/trie.(*FlatDbSubTrieLoader).iteration(0xc00064c000, 0xc0007af500, 0xc0007af4d8, 0x7f5049c50700, 0x3, 0x3)
        /home/andrey_ashikhmin/turbo-geth/trie/flatdb_sub_trie_loader.go:368 +0x1f6b
github.com/ledgerwatch/turbo-geth/trie.(*FlatDbSubTrieLoader).LoadSubTries.func1(0xc0000c8000, 0x47d600, 0xc0000c8000)
        /home/andrey_ashikhmin/turbo-geth/trie/flatdb_sub_trie_loader.go:552 +0x35b
github.com/ledgerwatch/bolt.(*DB).View(0xc000236e00, 0xc0007af5c8, 0x0, 0x0)
        /home/andrey_ashikhmin/go/pkg/mod/github.com/ledgerwatch/bolt@v1.4.5-0.20200504044242-1f3c42ebc79a/db.go:695 +0x8e
github.com/ledgerwatch/turbo-geth/trie.(*FlatDbSubTrieLoader).LoadSubTries(0xc00064c000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/andrey_ashikhmin/turbo-geth/trie/flatdb_sub_trie_loader.go:533 +0xe5
github.com/ledgerwatch/turbo-geth/trie.(*SubTrieLoader).LoadFromFlatDB(0xc00021d720, 0x1664980, 0xc0001dcd50, 0x163a480, 0xc000396080, 0xc00021d660, 0x1, 0x1, 0xc0006400a0, 0x1, ...)
        /home/andrey_ashikhmin/turbo-geth/trie/sub_trie_loader.go:67 +0x219
github.com/ledgerwatch/turbo-geth/trie.(*SubTrieLoader).LoadSubTries(...)
        /home/andrey_ashikhmin/turbo-geth/trie/sub_trie_loader.go:59
[out.log.zip](https://github.com/ledgerwatch/turbo-geth/files/4639981/out.log.zip)

**Comment by AlexeyAkhunov** [comment]
I have so far figured out that at least one leaf pages got "blanked" out, which makes a number of leaves in CurrentStateBucket irretrievable. cursor.Next() skips over the missing page, but both Seek and SeekTo fail when they land on that empty page. Since the process was up for about 7 days before it happened, I do not see if happening because of abrupt shutdown. Currently I am not sure if it is bolt/OS or even hardware issue. There does not seem to be place in bolt code case that would write a blank page, but I need to re-confirm

**Comment by AlexeyAkhunov** [comment]
It is completely blank
````
alexeyakhunov@Alexeys-MacBook-Pro bolt % go run cmd/bolt/main.go page /Volumes/tb4/turbo-geth/geth/chaindata 74366891
Page ID:    0
Page Type:  unknown<00>
Total Size: 4096 bytes
alexeyakhunov@Alexeys-MacBook-Pro bolt % go run cmd/bolt/main.go dump /Volumes/tb4/turbo-geth/geth/chaindata 74366891
46ebfab000 0000 0000 0000 0000 0000 0000 0000 0000
46ebfab010 *
46ebfabff0 0000 0000 0000 0000 0000 0000 0000 0000
````

**Comment by AlexeyAkhunov** [comment]
Closing this as we are pivoting from BoltDB
