### ISSUE TITLE
saving the ETL loading key in the Stage State might not always work for IntermediateHashes bucket

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#682]
the current logic of saving the ETL loading key in the Stage State might not always work for IntermediateHashes bucket
because `NextKey` in the etl package produces the next possible key which is of the same length
which is a good assumption for all buckets, except for IntermediateHashes
where this approach may skip legitimate records, which are longer than the current key, but have the same prefix
the solution should be easy - remove NextKey and replace this condition
`if bytes.Compare(k, args.LoadStartKey) < 0 { return nil}` with `if bytes.Compare(k, args.LoadStartKey) <= 0 { return nil}` in collector.go

**Comment by mandrigin** [comment]
it looks like that there is no `LoadStartKey` anymore, closing this issue
