### ISSUE TITLE
Docker Build Fails Step 3/11 : COPY

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/turbo-geth#832]
#### System information
```
docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

#### Expected behaviour
Docker build should work.

#### Actual behaviour

```
PS > Get-Content .\Dockerfile | docker build -
Sending build context to Docker daemon   2.56kB
Step 1/11 : FROM golang:1.14-alpine as builder
1.14-alpine: Pulling from library/golang
df20fa9351a1: Already exists
ed8968b2872e: Pull complete
a92cc7c5fd73: Pull complete
00abe362642d: Pull complete
e0491c15e88f: Pull complete
Digest: sha256:d6deb50437547fd7226890aa19b075fbf7f5063e3c0d7a2eaf7fb41d11069013
Status: Downloaded newer image for golang:1.14-alpine
 ---> 30df784d6206
Step 2/11 : RUN apk add --no-cache make gcc musl-dev linux-headers git
 ---> Running in 4fe8cd3f23d2
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/19) Installing libgcc (9.3.0-r2)
(2/19) Installing libstdc++ (9.3.0-r2)
(3/19) Installing binutils (2.34-r1)
(4/19) Installing gmp (6.2.0-r0)
(5/19) Installing isl (0.18-r0)
(6/19) Installing libgomp (9.3.0-r2)
(7/19) Installing libatomic (9.3.0-r2)
(8/19) Installing libgphobos (9.3.0-r2)
(9/19) Installing mpfr4 (4.0.2-r4)
(10/19) Installing mpc1 (1.1.0-r1)
(11/19) Installing gcc (9.3.0-r2)
(12/19) Installing nghttp2-libs (1.41.0-r0)
(13/19) Installing libcurl (7.69.1-r0)
(14/19) Installing expat (2.2.9-r1)
(15/19) Installing pcre2 (10.35-r0)
(16/19) Installing git (2.26.2-r0)
(17/19) Installing linux-headers (5.4.5-r1)
(18/19) Installing make (4.3-r0)
(19/19) Installing musl-dev (1.1.24-r9)
Executing busybox-1.31.1-r16.trigger
OK: 163 MiB in 34 packages
Removing intermediate container 4fe8cd3f23d2
 ---> b4bb5a6aa06f
Step 3/11 : COPY go.mod go.sum /app/
COPY failed: stat /var/lib/docker/tmp/docker-builder822170195/go.mod: no such file or directory
```

#### Steps to reproduce the behaviour
From PowerShell:
```
git clone https://github.com/ledgerwatch/turbo-geth.git
cd turbo-geth
Get-Content .\Dockerfile | docker build -
```

**Comment by AskAlexSharov** [comment]
Looks like docker doesn’t understand which folder need to build. Try “docker build . -“ or “docker build - .”
Or without Get-Content, I usually do: “docker build -t turbo-geth .”

**Comment by MysticRyuujin** [comment]
Ok, I did `docker build -t turbo-geth .` and it got a lot further but it still failed...

```
<truncated>
...
Done building.
Run "./build/bin/tg" to launch turbo-geth.
Removing intermediate container 04c84072700f
 ---> 8c3409f700a0
Step 7/11 : FROM alpine:latest
latest: Pulling from library/alpine
df20fa9351a1: Already exists
Digest: sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
Status: Downloaded newer image for alpine:latest
 ---> a24bb4013296
Step 8/11 : RUN apk add --no-cache ca-certificates
 ---> Running in 0c02231b0f0b
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/1) Installing ca-certificates (20191127-r4)
Executing busybox-1.31.1-r16.trigger
Executing ca-certificates-20191127-r4.trigger
OK: 6 MiB in 15 packages
Removing intermediate container 0c02231b0f0b
 ---> 98aa9e2854e7
Step 9/11 : COPY --from=builder /app/build/bin/geth /usr/local/bin/
COPY failed: stat /var/lib/docker/overlay2/c8a7da7a4e1818e4a44c1ce6649a7fc2572fb866b42b2c258f0f56b2aa90a381/merged/app/build/bin/geth: no such file or directory
```

**Comment by mandrigin** [comment]
It is a wrong executable name in the docker file.

In these lines:

```
COPY --from=builder /app/build/bin/geth /usr/local/bin/

EXPOSE 8545 8546 8547 30303 30303/udp
ENTRYPOINT ["geth"]
```

try to replace it with 

```
COPY --from=builder /app/build/bin/tg /usr/local/bin/

EXPOSE 8545 8546 8547 30303 30303/udp
ENTRYPOINT ["tg"]
```

**Comment by MysticRyuujin** [comment]
It completed after making the above changes. I'll play with it now 😄

**Comment by MysticRyuujin** [comment]
Somewhat related question: This is only building `tg` and not any of the RPC stuff, right? E.G. `rpcdaemon`?

**Comment by AskAlexSharov** [comment]
There is file: Dockerfile.alltools

**Comment by mandrigin** [comment]
@MysticRyuujin if I can ask you to try building Docker in this branch and check if your Docker issue is fixed there: https://github.com/ledgerwatch/turbo-geth/pull/834

**Comment by MysticRyuujin** [comment]
I haven't done an extensive tests or anything but the following worked:

```
git clone -b 832-dockerfile-fixup --single-branch https://github.com/ledgerwatch/turbo-geth.git
cd turbo-geth
docker build -t turbo-geth .
```

I've temporarily given up going the Docker route since it's not all that clear to me how to run the individual pieces together, so I just spun up a Linux VM instead.

**Comment by AskAlexSharov** [comment]
@MysticRyuujin - what is 1-st thing you will try to test after build done? If I know your use-case, then maybe I can create for it  docker-compose.yaml

**Comment by MysticRyuujin** [comment]
So right now I'm just trying to get a feel for how to run the services, how long it'll take to sync, disk requirements, etc. and then additionally I just want to "poke it"

What I have setup, which to me seems like a common use case, is

1. Three `supervisor` services (could also be systemd, or 3 individual dockers).
  a. `/opt/turbo-geth/build/bin/tg --datadir=/data/tg --identity MysticRyuujin-TurboGeth --port 30304 --private.api.addr=localhost:9090`
  b. `/opt/turbo-geth/build/bin/rpcdaemon --chaindata /data/tg/tg/chaindata --http.addr="0.0.0.0" --http.vhosts="*" --http.corsdomain="*" --http.api="eth,debug"`
  c. `/opt/turbo-geth/build/bin/restapi --private.api.addr=localhost:9090`

I'm aware that with `b` I could go with the remote API here, instead of `chaindata`, probably best for the docker setup...

If that was dockerized, I could see that being a common setup/scenario for a lot of people.

**Comment by AskAlexSharov** [comment]
Thanks for extended answer. 
FYI: “make run-web-ui” starts page which using restapi, there is no useful features, but can see how much space takes every bucket in DB.

**Comment by MysticRyuujin** [comment]
What exactly does "run-web-ui" do? I run headless, does it generate a new binary that hosts a webpage or is this suppose to be ran on a non-headless machine and it just brings up a browser window?

**Comment by AskAlexSharov** [comment]
Yes, it opens browser. But it can be run on another machine and ui will have button to set address:port of restapi.

**Comment by MysticRyuujin** [comment]
It appears that requires dependencies that are not listed (yarn?)

**Comment by AskAlexSharov** [comment]
yes, it's javascript package manager (probably will also require `node`). 
deps are listed in: https://github.com/ledgerwatch/turbo-geth/tree/master/debug-web-ui#prerequisites

I will add this dependencies to docker-compose and other docs.

**Comment by AskAlexSharov** [comment]
@MysticRyuujin done with docker-compose:
docs: https://github.com/ledgerwatch/turbo-geth/pull/841/files#diff-04c6e90faac2675aa89e2176d2eec7d8R138
docker-compose.yml: https://github.com/ledgerwatch/turbo-geth/pull/841/files#diff-4e5e90c6228fd48698d074241c2ba760R1

Anything else you need?

**Comment by MysticRyuujin** [comment]
This is awesome. I'll play with it but you can consider this closed. For my own education though it would appear that I need to follow the instructions 1-4 prior to running step 5 in order to build/run the docker, is that correct?

I only ask because that's difficult to do on Windows, it's not a problem for me but others might find it helpful for there to be a hub.docker.com to pull from 😉

**Comment by MysticRyuujin** [comment]
I don't know if it's possible...but...in order to run this docker on a windows host I think you need to include `--ipcdisable` I've never gotten Geth to run hosted on Windows without that command.

Not sure the best way to handle that though...as I'm sure it's useful for other people.

**Comment by MysticRyuujin** [comment]
So, because I'm running Turbo-Geth on another machine right now, I wanted to just build the debugui to check it out.

So I cloned/pulled the latest master and I did:
```
cd turbo-geth\debug-web-ui
docker build -t debugui .
```

I got this warning (not sure if it means anything):
```
[3/4] Linking dependencies...
warning " > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
```

Then I tried to launch it:
```
docker run --name debugui -p 3000:3000 --network my-bridge debugui
yarn run v1.22.4
$ react-scripts start
ℹ ｢wds｣: Project is running at http://172.18.0.7/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /app/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...

Done in 1.18s.
```

**Comment by AskAlexSharov** [comment]
"instructions 1-4 prior to running step 5" - oh, actually digits in Readme are independent, probably need to mention it somehow (or just convert digits to list).

"there to be a hub.docker.com to pull from" - we will add a bit later

"--ipcdisable" - right, I will add now

"warnings from debug UI" - it's ok, it's warnings from some dependency lib. Can disable them on current package manager: https://github.com/yarnpkg/yarn/issues/6672

"Done in 1.18s." - I just released docker-compose.yml file, you can see example of run parameters there. That frontend server requires `stdin_open: true` to show logs and don't stop. I also added section to Readme about docker-compose. Maybe some day we will embed UI files into restapi binary.

**Comment by MysticRyuujin** [comment]
Hmmm, was looks for the docker run equivalent to stdin_open: true but maybe I didn't look hard enough, I'll try again tomorrow

**Comment by AskAlexSharov** [comment]
Not 100% sure, but I think it's `-it`

**Comment by AskAlexSharov** [comment]
Just that server inside UI docker is interactive - it may ask you some questions depends on it's mood
