### ISSUE TITLE
Feature Request: Support for EthStats

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/turbo-geth#835]
How am I suppose to flex on people if EthStats isn't supported? 😆 

As far as I can tell there doesn't appear to be support for EthStats? Attempting to use the --ethstats flag results in this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x101667e]

goroutine 214 [running]:
github.com/ledgerwatch/turbo-geth/ethstats.(*Service).loop(0xc000252cc0)
        github.com/ledgerwatch/turbo-geth@/ethstats/ethstats.go:147 +0x15e
created by github.com/ledgerwatch/turbo-geth/ethstats.(*Service).Start
        github.com/ledgerwatch/turbo-geth@/ethstats/ethstats.go:118 +0x5a
```

Also, I could be mistaken but I don't THINK `tg` or `rpcdaemon` have the necessary API endpoints required to run the standalone ethstats client?

**Comment by AlexeyAkhunov** [comment]
Good point, we did not think of that, thanks for pointing this out
