### ISSUE TITLE
Use XDG directories for application files

### ISSUE THREAD

**Issue by pipermerriam** [ledgerwatch/turbo-geth#836]
#### Expected behaviour

For turbo geth to not place things at the top level in my home directory (even if they are *hidden* files :smile: ) but instead to use the [XDG standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and to place things somewhere like `$XDG_DATA_HOME/turbogeth`

#### Actual behaviour

The client creates a hidden directory under `$HOME/.turbogeth` where it stores things

#### Steps to reproduce the behaviour

Run the client

**Comment by mandrigin** [comment]
@pipermerriam so is the correct behaviour will be to use `$XDG_DATA_HOME/turbogeth` if `$XDG_DATA_HOME` is set, but use `$HOME/.turbogeth` otherwise?

**Comment by pipermerriam** [comment]
The spec defines defaults for when these variables are not set:

>  $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used. 

You can see our simple python module that we use for these directories which also shows the defaults: https://github.com/ethereum/trinity/blob/master/trinity/_utils/xdg.py

**Comment by mandrigin** [comment]
@pipermerriam https://github.com/ledgerwatch/turbo-geth/issues/836 here is the support for XDG (linux only at the moment, because Mac uses a bit different dir structure)

**Comment by AskAlexSharov** [comment]
cool. Also added it for tg/prometheus/grafana databases in docker: https://github.com/ledgerwatch/turbo-geth/pull/841/files#diff-4e5e90c6228fd48698d074241c2ba760R1
