### ISSUE TITLE
Feature request: rework SyncStageProgress to gain forward-compatibility

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/turbo-geth#855]
Need re-think SyncStageProgress bucket. Next properties are expected:
- Now introduction of new stage "in the middle" is breaking-change. Need store stages in forward-compatible way. (For example if we will need to add 1 new stage between stage 3 and stage 4).
- Same about remove stage in future
- Same about re-ordering of stages (means sequential number of stage must not be stored in DB - only hardcoded in code).

**Comment by AlexeyAkhunov** [comment]
If we introduce stage names instead of numbers, and set up the ordering in the code, this should work, right?

**Comment by AskAlexSharov** [comment]
probably - yes.
