### ISSUE TITLE
Implement `trace_filter` JSON RPC method

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#880]
https://openethereum.github.io/wiki/JSONRPC-trace-module#trace_filter

Required for migration of the graph protocol

**Comment by AlexeyAkhunov** [comment]
Some test vectors: https://github.com/Great-Hill-Corporation/trueblocks-core/tree/develop/src/other/trace_filter

**Comment by koen84** [comment]
Would be great to see this (and other trace_* methods) implemented.  Thanks

**Comment by tjayrush** [comment]
I think this issue can probably be closed. While `trace_filter` needs work, it's being tracked in issue #1119

**Comment by tjayrush** [comment]
Closing due to already being tracked in the above-mentioned issue.
