### ISSUE TITLE
Allow block number to be integer and not necessarily hex string in eth_getBlockByNumber in RPC daemon

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#899]
The effect is that the block number can be provided as an integer and not necessarily as a hex string

**Comment by akme** [comment]
Trying to use turbo-geth with The Graph indexer and getting an error:
```
Aug 15 09:41:39.219 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #17) with result Err(Decoder("Error(\"invalid type: number, expected a 0x-prefixed hex string with length between (0; 64]\", line: 0, column: 0)"))
```
would be nice to get it working with number and not hex

**Comment by AlexeyAkhunov** [comment]
Fixed by: https://github.com/ledgerwatch/turbo-geth/pull/1007
