### ISSUE TITLE
net_version using hardcoded interface

### ISSUE THREAD

**Issue by koen84** [ledgerwatch/turbo-geth#957]
I compiled the 2020-08-03 release, yet the net_version method isn't working.  It seems it has 127.0.0.1:9090 hardcoded, rather than interfacing as configuration is setup.

I run `./build/bin/rpcdaemon --chaindata ~/Library/TurboGeth/tg/chaindata --http.api=eth,debug,net` so it's accessing files on disk directly, which works fine for other methods (they don't try opening localhost port 9090).

**Comment by AlexeyAkhunov** [comment]
@koen84 is this still an issue for you?

**Comment by koen84** [comment]
Yes, running commit 050ef87 and net_version is looking directly for 127.0.0.1:9090
Also #958 consistently returns "block not found" when running with direct file access.

As a way around i'm currently testing with `private.api.addr`
