### ISSUE TITLE
Large amount of tg-sync-sortable-buf files and old ones not getting removed + wrong trie root after an unwind

### ISSUE THREAD

**Issue by koen84** [ledgerwatch/turbo-geth#969]
The tg-sync-sortable-buf<9numbers> amount for 272 GiB.  These files are 283-285MiB in size.  And while i see the log mentioning it's removing some, the total amount is still growing.  It seems what's cleanup are newly created files, the old ones all remain.  Did it leave files it forgot ?  What would be the effect of stopping turbogeth, removing all these files and starting turbogeth ?

I'm running Ubuntu 18.04 LTS.  

A few days ago turboget ran out of diskspace.

It keeps "resetting" in phase 5, because it runs across `Synchronisation failed, retrying         err="wrong trie root`

**Comment by koen84** [comment]
Here are a few iterations.  It's the first time i see the unwind stuff.  Seeing it's different hashes and different starting blocks, i figure it's moving ahead anyway, maybe suboptimal / slower.
[turbogeth200823.log](https://github.com/ledgerwatch/turbo-geth/files/5114394/turbogeth200823.log)

This server runs on masterbranch from 10 aug.  I figured i'd let it sort itself out before upgrading (and maybe meanwhile some more things get improved).

**Comment by AlexeyAkhunov** [comment]
Ok, thank you! I have had a similar issue and I suspect this is a genuine bug in the unwind, will investigate on my copy of the data. I will rename the issue

**Comment by koen84** [comment]
Let me know if you need anything else, i'd love to see turbogeth fully functional.

It's the first time i see the unwind messages though.  And even now, it seems to have happened only once out of several times it "resets" over `wrong trie root`

**Comment by koen84** [comment]
I'm wondering if the stage 5 "reset" is leading to temp files being "abondonned" of sorts (leading to an increase of their total disk usage) ?

**Comment by AskAlexSharov** [comment]
We definitely beed to check abandoned files more often, now we check only if we write buf files again, but it may never happen, because only if changes in DB are bigger than 128Mb we start using buf files.

**Comment by AskAlexSharov** [comment]
And also we need: lock buf files folder. It’s easy to run 2 instances which will conflict.

**Comment by mandrigin** [comment]
I’ll they conflict though? If you give them the same datadir you will probably have problems with the db first. And temp files are created with some random numbers in their names.

**Comment by AskAlexSharov** [comment]
I runing tg without Explicit flag of tmpdir, as a resul multiple instances sharing same tmp folder. Probably when you remove tmp files you will remove one belonged to another instance as well

**Comment by mandrigin** [comment]
I keep a list of files to be removed... I don’t just nuke everything. Also if you don’t specify anything the temp files should be in your datadir anyway. 

There was a bug about that before. /tmp can be mounted to a drive with lower capacity, so we want to avoid side effects of that.

**Comment by AskAlexSharov** [comment]
If you don’t nuke everything then you will never remove abandoned files

**Comment by mandrigin** [comment]
True, and that is what is going on with this Issue believe. If the node gets killed in the process of generating temp files, it will never touch them.
But I guess since we can’t really get conflicts on the temp files without conflicts for the database, we can remove all outstanding temp files on the node startup.

**Comment by mandrigin** [comment]
Though these files leftovers are a sign that the app gets killed (or crashes) mid-ETL operation (maybe unwinds). Last time when I killed the node during the unwind of intermediate hashes, I ended up with the broken state root and had to re-sync again.

I wonder if we can have some option or heuristics to reset the hashes, so in case of broken db we can rebuild everything from scratch.

**Comment by AskAlexSharov** [comment]
I just found something related to it, after restart we construct unwindStack in wrong order - it cause root mistmatch. I will make PR in couple hours.

**Comment by AskAlexSharov** [comment]
“ But I guess since we can’t really get conflicts on the temp files without conflicts for the database” we can, just start 2 nodes with different —datadir And not specified —tmpdir

**Comment by koen84** [comment]
@mandrigin i don't see crashes (or even restarts), just when in stage 5 it encounters "wrong root trie" it goes back to stage 1.

**Comment by AskAlexSharov** [comment]
@koen84  We Just fixed it
