### ISSUE TITLE
rpcdaeom and restapi have different methods of setting listening port

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/turbo-geth#985]
The difference between `rpcdaemon` and `restapi` is confusing.

`restapi` takes the format of `--http.addr="0.0.0.0:9092"`

`rpcdaemon` requires the port to be specified separately `--http.addr="0.0.0.0"` and `--http.port=9091`

Would be nice if they were unified.

**Comment by AskAlexSharov** [comment]
fixed restapi in: https://github.com/ledgerwatch/turbo-geth/pull/993
