### ISSUE TITLE
Please support eth_syncing

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/turbo-geth#986]
At ArchiveNode.io we use a fault tolerant load balancer called `dshackle` which continually queries our nodes with calls like `eth_getBlockNumber`, `eth_getBlockByNumber`, and `eth_syncing` in order to get the status of each individual node and figure out if any of our nodes are lagging or stuck. It then redirects queries based on the health and status of the node.

We'd really like to include Turbo-Geth nodes into ArchiveNode.io at some point, but right now not having `eth_syncing` as an available RPC endpoint is a show stopper for us.

Thanks :pray:

**Comment by AskAlexSharov** [comment]
Here you go: https://github.com/ledgerwatch/turbo-geth/pull/991

**Comment by AskAlexSharov** [comment]
@MysticRyuujin , this method is a bit irrelevant for TG. Can you give us more details - how you using it? What you wanna see there? What can we do to make it more useful for you?

**Comment by MysticRyuujin** [comment]
So that's really hard for me to answer as I don't know all of the inner workings of dshackle...

What I assume is that under normal operating conditions it is basically irrelevant for most nodes...after all, it's `false` the overwhelming majority of the time.

But, when a node goes offline for a bit and then comes back online, it hears about the latest blocks from peers and then it reports back "I'm on block x, highest block I know about is y"

I assume dshackle uses this information to determine the lag for that node, and/or knows not to send it requests for "latest" block when it's in the middle of syncing.

But again, I'm mostly speculating, I know that not having `eth_syncing` results in dshackle marking the node as unavailable right now.

I can toggle an option in dshackle to disable validation (something designed for Infura) but that would result in all of the health checks being turned off, which would be bad if the node got stuck.

**Comment by splix** [comment]
Thanks @MysticRyuujin. Let me also add some details. [Dshackle](https://github.com/emeraldpay/dshackle) is a load balancer whose job is to dispatch requests only to fully synchronized nodes. To verify the state of a node, it makes several requests, such as `eth_syncing` and `net_peerCount`. If a node is syncing, or doesn't have enough peers (say less than 3, which probably means that the nodes is too fresh and may not know yet that is needs to start syncing) then it's marked as a _non-OK_ node and requests are not routed to it until it gets fully synced and healthy.

**Comment by AlexeyAkhunov** [comment]
Should be fixed in here: https://github.com/ledgerwatch/turbo-geth/pull/991
