### ISSUE TITLE
Enable WebSockets support in rpcdaemon

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#996]

**Comment by MysticRyuujin** [comment]
FYI I see that some work was done on the WebSocket config but it doesn't appear to be working, yet.

```
POST / HTTP/1.1
content-type: application/json
user-agent: ReactorNetty/0.9.7.RELEASE
host: 192.168.10.50:9091
accept: */*
content-length: 59

{"jsonrpc":"2.0","id":1,"method":"eth_syncing","params":[]}
```

```
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Sec-Websocket-Version: 13
X-Content-Type-Options: nosniff
Date: Tue, 01 Sep 2020 22:21:01 GMT
Content-Length: 12

Bad Request

```

**Comment by Giulio2002** [comment]
Did you run daemon with`--ws`?

**Comment by MysticRyuujin** [comment]
Yes

Actually I take it back, `eth_syncing` isn't working at all now even over normal RPC with `--ws` flag is used. If I remove the `--ws` flag it works.

```
chase@RYUUJIN:~$ curl -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","id":1,"method":"eth_syncing","params":[]}' http://localhost:9091
Bad Request
```

```
chase@RYUUJIN:~$ curl -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","id":1,"method":"eth_syncing","params":[]}' http://localhost:9091
{"jsonrpc":"2.0","id":1,"result":{"currentBlock":"0xa475b3","highestBlock":"0xa475b5"}}
```
The only difference is the `--ws` flag

**Comment by Giulio2002** [comment]
curl should not be used for websockets try `wscat`

**Comment by MysticRyuujin** [comment]
Are you trying to say that I can either run with or without websocket, not both? That's not how Geth does it.

Also, the very 1st example I gave you WAS via Websocket, WITH `--ws`

**Comment by Giulio2002** [comment]
ok, so i made `--ws` only run websocket and i can fix that if that's not expected behaviour. but i think that curl is not appropriated to be adoperated with websockets. I used `wscat` to test websockets, with curl you should try with this (i think): https://gist.github.com/htp/fbce19069187ec1cc486b594104f01d0. you can also try `websocat`.

**Comment by MysticRyuujin** [comment]
Ok, that makes sense. I think I'm dealing with 2 problems.

Problem 1 being that turning on WebSocket turns off JSON RPC :smile: 

Problem 2 is is actually unrelated - it looks like when my front end makes the WebSocket connection it tries to do a subscribe:
`{"jsonrpc":"2.0","method":"eth_subscribe","params":["newHeads"],"id":1}`

Turbo-Geth replies with
`{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"no \"newHeads\" subscription in eth namespace"}}\n`

And then my front end closes the WebSocket and tries to use JSON RPC.

:facepalm: 

Not your problem lol

**Comment by Giulio2002** [comment]
To resume, you only need both json-rpc and websocket to work at the same time, yes? I did not get whether in problem 2 you were being sarcastic.

**Comment by MysticRyuujin** [comment]
Correct, I would like it if JSON RPC and WebSocket can be used at the same time.

I was just letting you know why I thought WebSocket was broken...I assume it does indeed work, my 2nd problem is not directly related to your work on WebSockets, just an incompatibility.

Thank You!

**Comment by Giulio2002** [comment]
Problem solved with #1030

**Comment by Giulio2002** [comment]
#1030

**Comment by AlexeyAkhunov** [comment]
It works now
