### ISSUE TITLE
Add net_peerCount to RPC daemon but return a constant value of 25

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#997]
because this method will break our architectural separation, once we moved peer management into the Sentry (there can also be multiple sentries per code node).
so it is better not to spend too much effort in trying to extract this information via gRPC

**Comment by AskAlexSharov** [comment]
Done in https://github.com/ledgerwatch/turbo-geth/pull/991/commits/8324f010cf6f25fb2ac99e9fce43f40f426b70fb

**Comment by AlexeyAkhunov** [comment]
https://github.com/ledgerwatch/turbo-geth/pull/991
